### ISSUE TITLE
Render list of top-level static FAQ categories

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#10]
Acceptance criteria:

- After clicking on "I don't have a booking", page according to designs is shown: https://marvelapp.com/7iihb90/screen/39265594
- data fetched from GraphQL server

*Note*: only titles of FAQ categories are now real, subtitles are still static as we don't have such info available yet

**Comment by jalbertsr** [comment]
I see marvel and zeplin have different designs, I think the last version is the one on zeplin: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aa98f803820cb498e96a0d1

**Comment by MagdalenaAlmanova** [comment]
Good job 💯
