### ISSUE TITLE
ContentHeader width problem

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#104]
When integrating the component with frontend @jalbertsr noticed a problem with the `ContentHeader` width as seen in the image below

![screen shot 2018-04-19 at 16 52 40](https://user-images.githubusercontent.com/2466887/38999575-6dd38f5a-43f2-11e8-8639-5cddcf9e852d.png)

**Comment by jalbertsr** [comment]
Screenshot related: https://github.com/kiwicom/smart-faq/issues/28#issuecomment-382855371
