### ISSUE TITLE
Add Back arrow to breadcrumbs

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#109]
Some designs show a back arrow button to move backwards along the breadcrumbs. https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aaac0e38d835c7b25745c15

It seems only the logged-in FAQ shows that arrow, whereas the logged-out case does not. We should clarify that and add it to the app.
![image](https://user-images.githubusercontent.com/2466887/39114348-e85767c6-46de-11e8-9968-6b9deb8b2765.png)

**Comment by jaroslav-kubicek** [comment]
I have to disappoint you, but it's not correct according to designs: https://zpl.io/aM48YJr

There is no Back arrow when you are log out on static FAQs

**Comment by MagdalenaAlmanova** [comment]
Perfect 😃
