### ISSUE TITLE
Upcoming booking shows incorrect data

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#112]
How it should work correctly:

- Outbound is all legs that have `isReturn` as false
- Inbound is all legs that are related to return flight - `isReturn` is true
- On top of the `ONE_WAY` and `RETURN` flight bookings, there is a third option - `MULTICITY` (doesn't have designs yet)
- Show only outbound if booking is `ONE_WAY` - there are one or more Legs and none of them has `isReturn` set to true
- Inbound consists of all legs with `isReturn` set to true - these are return fligts
- If there is more than one Leg for inbound/outbound, show logo as the combination of up to 4 airlines logos (just like on the frontend, there is new orbit component for that)
- Upcoming booking is booking with the `Leg` that has departure time nearest to the current time & in future (so it can't be decided upon only one Leg, but it needs to be iterated over the all Legs in the list to find the correct booking) - might be worth to create GraphQL query for that, something like `upcomingBooking()`

**Comment by jaroslav-kubicek** [comment]
How to test:
- One way booking as only one Accordion with "Outbound" title
- Return booking has "Outbound" and "Inbound" Accordions: https://zpl.io/V0E5kgm
- Multicity booking has multiple Accordions with one title "Trips": https://zpl.io/adMXeDR


- will be easier after merging #149

**Comment by MagdalenaAlmanova** [comment]
Should be the text "outbound, return and destinations" bold? 
@jaroslav-kubicek
