### ISSUE TITLE
Header of static FAQs doesn't match designs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#118]
Related to #109 

Expected:
- Back button instead of "Sign in" in header when there are breadcrumbs (some subcategory or article detail is displayed)
- No back arrow next to the breadcrumbs

https://zpl.io/bP4wqjA
<img width="604" alt="screen shot 2018-04-25 at 17 44 43" src="https://user-images.githubusercontent.com/2174629/39256899-5e06f54a-48b0-11e8-8685-0616a3f09258.png">

Actual:
<img width="488" alt="screen shot 2018-04-25 at 17 43 16" src="https://user-images.githubusercontent.com/2174629/39256859-40b6a4ea-48b0-11e8-826a-96b3192b786d.png">

**Comment by jalbertsr** [comment]
Also when article comes from search, header should look like: 

![screenshot](https://i.gyazo.com/5e0b2d1011d61c77c79263a4bb1730e1.png)

**Comment by MagdalenaAlmanova** [comment]
The "back" button instead of "Sign in" button is ok, but "the back arrow next to the breadcrumbs" is still here. As you can see on the screenshot.
![screen shot 2018-05-09 at 14 50 01](https://user-images.githubusercontent.com/37298895/39815801-7eca8280-5399-11e8-8333-b8327fe1490c.png)
