### ISSUE TITLE
Fix auto deployment to now.sh

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#119]
Something broke at now.sh + circleci https://zeit.co/toni/kiwicomsmart-faq/mvncrvdohg?redirect=1

**Comment by jalbertsr** [comment]
suddenly it works now, black magic.

**Comment by jalbertsr** [comment]
reopen beacuse it works intermittently

**Comment by jalbertsr** [comment]
close to disscuss here -> #167
