### ISSUE TITLE
QueryRenderer throws error & show loading forever

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#127]
When incorrect language is passed to any FAQ query, e.g. `cz`, QueryRenderer throws unexpected error and loading is shown forever.

Caused by this bug in relay: https://github.com/facebook/relay/issues/2385

**Comment by git-toni** [comment]
So far this has been reproduced as such to "simulate" token expiration:

1. Login via kiwi login.
2. Check that bookings are retrieved allright
3. Change the value of the cookie containing the token
4. Make sure that it returns Error and not infinite loader

Any other suggestions?

![image](https://user-images.githubusercontent.com/2466887/39710200-67c681a2-521c-11e8-8f5e-e0c65a07c03a.png)
