### ISSUE TITLE
Update booking header

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#131]
<img width="520" alt="screen shot 2018-04-30 at 17 20 31" src="https://user-images.githubusercontent.com/2174629/39435311-52051986-4c9b-11e8-8b19-4c8f181e1e7d.png">

- Designs of booking header slighly changed - Booking id is above the bold header
- Select other booking is on the right side
- There is status

e.g. https://zpl.io/V0E5kgm

**Comment by kantord** [comment]
Is there a color palette for the possible status values? I could not find it on zeplin

Here are the possible status values:

```
const statusMap = {
  NEW: { text: 'New', color: 'black' },
  REFUNDED: { text: 'Refunded', color: 'black' },
  PENDING: { text: 'Pending', color: 'black' },
  CONFIRMED: { text: 'Confirmed', color: 'black' },
  CANCELLED: { text: 'Cancelled', color: 'black' },
  DELETED: { text: 'Deleted', color: 'black' },
  CLOSED: { text: 'Closed', color: 'red' },
  EXPIRED: { text: 'Expired', color: 'black' },
};
```

**Comment by jaroslav-kubicek** [comment]
open
pending
closed
info
#ffc345;

confirmed
#52cf26;

expired
cancelled
refunded and any othe
#171b1e; (just black one)

**Comment by kantord** [comment]
Thanks! See https://github.com/kiwicom/smart-faq/pull/139
