### ISSUE TITLE
Implement responsive designs for static FAQs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#135]
**Acceptance criteria**

- Show smart FAQ on frontend when accessing Kiwi page from mobile device
- Static FAQs look according to designs

https://zpl.io/2jldrrr

**Comment by jaroslav-kubicek** [comment]
@kantord make them separate

**Comment by kantord** [comment]
@jaroslav-kubicek too late hahahahah

**Comment by kantord** [comment]
We can create a separate issue and reference it in the same pull request though

**Comment by MagdalenaAlmanova** [comment]
I cannot test this because link https://introduce-smart-faq.fe.staging.kiwi.com  was not working. I will try it tomorrow.

**Comment by jalbertsr** [comment]
That's a good question, I can tell you in advance that this link won't work any more.
I will rise this question tomorrow in slack.
