### ISSUE TITLE
Add error feedback for FAQArticleComment 

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#144]
Whenever a comment cannot be sent for some reason, some notification should be shown.

Designs soon by @mjancik :slightly_smiling_face: 

Update: [Zeplin Design](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5af550153745ab9c208a2060)

**Comment by MagdalenaAlmanova** [comment]
Just minor things: The text "Feedback form failed" is slightly higher.. and "go to contact page" has a different font thickness.
Prototype v.
![screen shot 2018-05-31 at 22 41 05](https://user-images.githubusercontent.com/37298895/40807595-09cc745a-6525-11e8-816c-219b3008e874.png)
Demo v.
![screen shot 2018-05-31 at 22 41 31](https://user-images.githubusercontent.com/37298895/40807603-120a2892-6525-11e8-88fe-32aa81b60cb8.png)

Thanks

**Comment by jalbertsr** [comment]
The alerts we currently use are `<SystemMessage/>` from Orbit Component, we have to change all `<SystemMessage/>` components to the new `<Alert/>` component from the new Orbit release, I will open and issue for that.

**Comment by MagdalenaAlmanova** [comment]
Ok. Thanks for your explanation.  👍
