### ISSUE TITLE
Add link to manage my booking

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#147]
**Acceptance criteria**
- When I click on "Manage my booking", I'm redirected to that page

<img width="483" alt="screen shot 2018-05-07 at 16 00 31" src="https://user-images.githubusercontent.com/2174629/39705958-2e30e5f6-5210-11e8-90b9-e6c613163b4a.png">

Zeplin: https://zpl.io/adMXeDR

**Comment by MagdalenaAlmanova** [comment]
Perfect 💯
