### ISSUE TITLE
Format booking number according to desings

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#150]
Acceptance criteria
- booking number is divided by space into groups of three digits, just like CZ format for thousands 

<img width="314" alt="screen shot 2018-05-09 at 13 41 25" src="https://user-images.githubusercontent.com/2174629/39812945-e1aad310-538e-11e8-8ab4-79ade102624c.png">

Related to #146

**Comment by MagdalenaAlmanova** [comment]
The booking format is correct. Appart from the booking number I spotted, the` "select other booking" `has a small first letter but via design, there is capital. 

M.

**Comment by MRTNKCR** [comment]
Yes, let's change the first letter please.
