### ISSUE TITLE
Collapse multicity trips

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#156]
If multicity booking has more than 2 trips, show only first two with overlay effect and enable to show them all - by clicking on "Show all trips" **(Not Show all flights!)**

<img width="506" alt="screen shot 2018-05-10 at 15 46 38" src="https://user-images.githubusercontent.com/2174629/39872812-6c21a980-5469-11e8-880f-5999ceed8e4f.png">

Zeplin: https://zpl.io/bLw5z8Q

**Comment by MagdalenaAlmanova** [comment]
Only in Safari(11:1), it showed me this: 
![screen shot 2018-06-02 at 22 57 15](https://user-images.githubusercontent.com/37298895/40880871-44f5ca00-66b9-11e8-8005-efca148eb522.png)
Thanks

**Comment by MagdalenaAlmanova** [comment]
👍
