### ISSUE TITLE
Frontend integration login not working

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#171]
It seems smart-faq login is not working when integrated on https://introduce-smart-faq.fe.staging.kiwi.com/en/ since yesterday's branch rebase. We've got to fix it :slightly_smiling_face:

**Comment by jaroslav-kubicek** [comment]
Different versions of React caused this bug 🤦‍♂️

**Comment by git-toni** [comment]
This doesn't seem fixed, although it could be worth another issue on itself. Symptons:

- `Sign in` buttons are present even after having logged-in
![image](https://user-images.githubusercontent.com/2466887/40105484-5bd180d0-58f3-11e8-8306-8206511bdd14.png)

- After refresh, the whole session is gone.
