### ISSUE TITLE
Suggestion: Use more flexbox and fewer hardcoded px measurements

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#180]
**This is partially design related.**
The issue is that we have many hard coded measurements in the code, such as this:
```
margin-right: 149px;
```

Implementing alignments like that might be debilitating us long-term in terms of implementing design changes, especially when it comes to implementing responsive design. A lot of times it might mean having to implement the same thing for every breakpoint separately, while we might not need breakpoints at all in many cases if we use 'flexbox'.

My proposal is that we should:
- Avoid hard coded measurements whenever possible
- Implement alignment using flexbox, or more classical alternatives, so we can avoid manual alignment
- Aim to use a "palette" or "inventory" of a few specific measurement values for font sizes and spacings. (i.e. `sp-sm: 16px`, `sp-md: 24px` etc..)

As an extra regarding the "inventory" or "palette": it might be a nice idea to aim for a consistent vertical rhythm. This is just a personal opinion, but I think it'd be nice if spacings, font sizing and vertical measurements (such as card height) should be integer multiples of the same number.

I know this is a huge ask and it probably cannot be part of our current scope, but better yet, we could do a baseline alignment, i. e. non-typographical elements and typographical elements with different typesetting would be aligned to the same baseline. Here's an article that explains what I mean: https://www.smashingmagazine.com/2012/12/css-baseline-the-good-the-bad-and-the-ugly/

**Comment by git-toni** [comment]
Regarding the flexbox point and moving away from pixel-perfectness, I agree with you. I think we should consider this approach since we will need the app to be reliably well rendered across several devices(diff screen-sizes) and browsers. Not aiming for pixel-perfection but for a "consistent" design can ease this task.

> it might be a nice idea to aim for a consistent vertical rhythm [...] should be integer multiples of the same number.

This is too philosophically deep, don't have a personal opinion yet :smile:  Interesting tho

cc @mjancik

**Comment by mjancik** [comment]
Vertically the designs are based on our 4px grid which we are all following when creating the designs. There might be very specific exceptions but as for now our Orbit guidelines consist of these vertical spacings: Desktop: 4, 8, 12, 16, 24, 32, 40, 52 (in px) / Mobile: 4, 8, 12, 16, 20, 28, 36, 44 (in px).

**Comment by jalbertsr** [comment]
since is a suggestion and we all agree we should use more flex-box and fewer hardcoded px measurements can we close the issue? @kantord

**Comment by kantord** [comment]
Yup!
