### ISSUE TITLE
Resolve differences from designs in FAQs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#183]
FAQ item
<img width="416" alt="screen shot 2018-05-16 at 18 43 01" src="https://user-images.githubusercontent.com/2174629/40131095-41517c1a-5939-11e8-965f-eaddf69d39e4.png">

- Perex should have line-height: 1.4
- There should be a 5px margin between Header and perex

Feedback button
<img width="427" alt="screen shot 2018-05-16 at 18 53 35" src="https://user-images.githubusercontent.com/2174629/40131548-81a04f2a-593a-11e8-8f90-93d495d91293.png">

- button needs to be aligned to the centre

Acceptance criteria
- All mentioned issues perfectly match the designs in Zeplin

**Comment by kantord** [comment]
Resolved differences regarding spacing/typography of perex.

The contact button looks like this on my computer:
![2018-05-23-113049_1012x295_scrot](https://user-images.githubusercontent.com/3704904/40416291-3519eff6-5e7d-11e8-8ebe-130c9b5d950f.png)

@jaroslav-kubicek, is there a specific step I need to make to reproduce the issue?

**Comment by jalbertsr** [comment]
@kantord  this only happens on https://introduce-smart-faq.fe.staging.kiwi.com/en/

**Comment by kantord** [comment]
@jalbertsr wow! :-D haha now I see it!

**Comment by kantord** [comment]
@jalbertsr Ok so apparently the issue was that the button had `display: block` in frontend and `display: inline-block` in SmartFAQ (global styles/reset or something)

I pushed a solution which centers the button using `display: flex`, that should equally work with `block` and `inline-block`.

**Comment by MagdalenaAlmanova** [comment]
Perfect 💯 👍
