### ISSUE TITLE
Login don't work when going back from FAQ

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#184]
Repro steps
- Click on "I don't have booking"
- Click on "Sign in" in header
- Sign in via email/password

Expected
- Booking page is displayed as usual

Actual
- Blank page is displayed

<img width="836" alt="screen shot 2018-05-16 at 18 57 50" src="https://user-images.githubusercontent.com/2174629/40131922-9a946f42-593b-11e8-810a-a978c6add022.png">

**Comment by jalbertsr** [comment]
Solved by https://github.com/kiwicom/smart-faq/pull/227
