### ISSUE TITLE
Fix styles in header

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#186]
<img width="339" alt="screen shot 2018-05-16 at 19 21 14" src="https://user-images.githubusercontent.com/2174629/40133086-f1a2eeaa-593e-11e8-89c0-61e50a5df3b7.png">

- text in both link should be bold
- color of X close icon should be `#46515e`

**Comment by MagdalenaAlmanova** [comment]
`"Full FAQ site"` and `"Sign out"` are on the wrong site. 
**_demo v._**
![screen shot 2018-05-28 at 20 52 37](https://user-images.githubusercontent.com/37298895/40626643-38522896-62ba-11e8-9fcc-2e47db4b783e.png)

**_prototype v._**
![screen shot 2018-05-28 at 21 01 44](https://user-images.githubusercontent.com/37298895/40626674-5cc24a94-62ba-11e8-9d55-a443e20a1215.png)

Thanks
