### ISSUE TITLE
Create check inbox email page

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#20]
Acceptance criteria:

- Page according to design: [Marvel App](https://marvelapp.com/7iihb90/screen/39265578), [Zepplin Desing](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aa6b8a48e193557a2446de1)

**Comment by MRTNKCR** [comment]
ready for QA? @jalbertsr

**Comment by MagdalenaAlmanova** [comment]
Bug 1 - Text is unreadable on the last page. One text covers the other one,  ss you can see on the printscreen. 
![screen shot 2018-03-21 at 19 35 41](https://user-images.githubusercontent.com/37298895/37735279-dcc43b00-2d4d-11e8-9dce-ec092285d48b.png)

It was tested on macOS High Sierra 10.13.3 in **Safari** v. 11.0.3 and **Mozilla Firefox** v. 59.0.1. **I did not find this bug in Google Chrome and Opera, both latest versions.**

I have one question: when I compared the final prototype that is listed on this task with the test version, both the font and the pictures were quite bigger in the test version than in the prototype. Is it correct?

@jalbertsr 

Thanks.
Meggy

**Comment by MagdalenaAlmanova** [comment]
I found **two** little problems with this issue. The first one is : if I click on the button **"Get Help"** it returns me on the previous page **"Need help"** only in Safari. In Chrome, Firefox and Opera, this is not problem. The second problem occurs on the first page titled **"Need help"** where text **"Full FAQ site"** and **symbol** is not alligned in the row. You can see both on screenshots below: 

**_Prototype_** 
![screen shot 2018-03-22 at 21 05 48](https://user-images.githubusercontent.com/37298895/37795528-00c0350a-2e15-11e8-93f6-9e6e4e89aed2.png)

**_Demo_**
![screen shot 2018-03-22 at 21 05 55](https://user-images.githubusercontent.com/37298895/37795542-0955bd0c-2e15-11e8-8864-4971bfc3c820.png)

That is everything from my side.

Thank you.
Meggy

**Comment by MagdalenaAlmanova** [comment]
It looks great 👍  but I have one question: Is it correct when I do not input email/correct format of email address and after clicking on "**Get Help"**, it redirects me straight on the  **“Check inbox mail”** page? 

@jalbertsr 

Thank you,
Meggy

**Comment by jalbertsr** [comment]
Yes, so far is correct, because there is still no logic behind, but we'll implement it ASAP.

**Comment by MagdalenaAlmanova** [comment]
Perfect, Thank you 👍
