### ISSUE TITLE
Add contacts information related to booking

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#207]
Add phone no. & email on Single Booking page - data already available in GraphQL

<img width="512" alt="screen shot 2018-05-23 at 15 10 25" src="https://user-images.githubusercontent.com/2174629/40426469-7338d536-5e9b-11e8-80c2-7ef6a3df2438.png">

"Write us a message" should be just simple "mailto:..." link

Zeplin: https://zpl.io/adAW4xe

**Comment by dinodsaurus** [comment]
Could you just add screenshot/description where this needs to be added @jaroslav-kubicek

**Comment by jaroslav-kubicek** [comment]
aye, updated @dinodsaurus

**Comment by dinodsaurus** [comment]
Should I implement `mailto` to Orbit components?
https://kiwicom.github.io/orbit-components/?knob-Title=Primary%20link&knob-Text=Custom%20link&knob-Width=0&knob-Icon=Airplane&knob-Type=primary&knob-Size=normal&knob-URL=https%3A%2F%2Fkiwi.com&knob-Variation=filled&selectedKind=TextLink&selectedStory=Primary%20link&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
