### ISSUE TITLE
Fix AllBookings screen at Github Pages static deployment

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#216]
There seems to be an issue with the styled-jsx compiled files.

![image](https://user-images.githubusercontent.com/2466887/40373803-0163c4ec-5de8-11e8-8e84-07632e6aaa12.png)

**Comment by jalbertsr** [comment]
why doesn't it crash on now, local or staging? is gh pages as you suggested serving the files different? then maybe we should move to another deployment?

**Comment by git-toni** [comment]
It seems clearly linked to the way the files are served or bundled, and particularly related to `styled-jsx`. Whenever we deploy via static files, eg. github pages or surge(I'm using for the new deployment), we get the same errors, eg. https://sfq-hola.surge.sh/  (current static deployment of master).
