### ISSUE TITLE
fix back button in all booking page

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#226]
when bookings are loaded in all booking page, back button is displayed wrong

![screenshot](https://i.gyazo.com/7b2466a5aab0ae41137353a49ccd836d.png)

**Comment by jaroslav-kubicek** [comment]
will be fixed in #227

**Comment by jalbertsr** [comment]
Closed by https://github.com/kiwicom/smart-faq/pull/255
