### ISSUE TITLE
Create automated releases

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#24]
Might be interesting for us:
https://hackernoon.com/automate-npm-releases-with-semantic-release-and-human-written-change-logs-2adb1dce487

Acceptance tests:
- [ ] npm package is automatically published after merge when changing version in package.json.

**Comment by git-toni** [comment]
My suggestions: use hooks.
- Automatically `npm version patch` at `pre-commit`.
- Automatically `npm publish` at circleCI when merging to master. https://circleci.com/docs/1.0/npm-continuous-deployment/
- Do `minor` updates manually.
