### ISSUE TITLE
Make booking page responsive according to designs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#241]
Nonurgent:
<img width="362" alt="screen shot 2018-05-25 at 11 17 07" src="https://user-images.githubusercontent.com/2174629/40536657-3064d908-600d-11e8-879e-d04823a8b3c0.png">

Urgent expanded:
<img width="337" alt="screen shot 2018-05-25 at 11 20 20" src="https://user-images.githubusercontent.com/2174629/40536830-a4fe7d78-600d-11e8-9782-32f6af495a19.png">

Zeplin: 
Nonurgent: https://zpl.io/2Ej8K8M and following
Urgent expanded: https://zpl.io/aXzOnD8

**Comment by kantord** [comment]
If nobody else wants it I'll be happy to take assign myself to this issue. However it might be better to do it after this one is merged: https://github.com/kiwicom/smart-faq/pull/227 to avoid a bunch of merge conflicts

**Comment by kantord** [comment]
What should happen if the user clicks "Manage my booking" or "select another booking"?
