### ISSUE TITLE
Refactor all links to use new orbit components

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#248]
Use this component from orbit for links

https://kiwicom.github.io/orbit-components/?knob-Title=Primary%20link&knob-Variation=filled&knob-Type=primary&knob-Size=normal&knob-Width=0&knob-Icon=Airplane&knob-URL=https%3A%2F%2Fkiwi.com&selectedKind=TextLink&selectedStory=Primary%20link&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
https://kiwicom.github.io/orbit-components/?knob-Title=Secondary%20link&knob-Variation=filled&knob-Type=primary&knob-Size=normal&knob-Width=0&knob-Icon=Airplane&knob-URL=https%3A%2F%2Fkiwi.com&selectedKind=TextLink&selectedStory=Secondary%20link&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

<img width="199" alt="screen shot 2018-05-25 at 17 25 31" src="https://user-images.githubusercontent.com/2174629/40552685-bca71fce-6040-11e8-81c9-56b45268d96a.png">
<img width="234" alt="screen shot 2018-05-25 at 17 25 22" src="https://user-images.githubusercontent.com/2174629/40552686-bcef93b2-6040-11e8-8520-8fd5c55a3824.png">
<img width="310" alt="screen shot 2018-05-25 at 17 24 11" src="https://user-images.githubusercontent.com/2174629/40552687-bd2c0162-6040-11e8-80f6-11bab7bdde54.png">
<img width="310" alt="screen shot 2018-05-25 at 17 23 58" src="https://user-images.githubusercontent.com/2174629/40552688-bd56b736-6040-11e8-9f88-c34c7dc60b9c.png">
<img width="495" alt="screen shot 2018-05-25 at 17 23 46" src="https://user-images.githubusercontent.com/2174629/40552690-bd8e54ac-6040-11e8-8c88-c59510b36427.png">
<img width="120" alt="screen shot 2018-05-25 at 17 23 30" src="https://user-images.githubusercontent.com/2174629/40552692-bdd83cb6-6040-11e8-9c36-cca61415ccb5.png">

**Comment by radkag** [comment]
"Select other booking" - already is Orbit component
"Full FAQ site" - should wait for new release from Orbit components (in master in GitHub I can see the possibility of adding children to TextLink props and that's what we want here, because "Full FAQ site" comes with icon)

And in such case, don't we want to wait with this ticket and implement it later?

**Comment by MagdalenaAlmanova** [comment]
👍
