### ISSUE TITLE
Responsive design broken in landscape mode

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#260]
## iPhone SE portrait mode (works)
![2018-05-29-124719_776x1256_scrot](https://user-images.githubusercontent.com/3704904/40654432-a1539abc-633e-11e8-89d8-da49cebfa7fd.png)

## iPhone SE landscape mode (broken)
![2018-05-29-124653_1339x878_scrot](https://user-images.githubusercontent.com/3704904/40654433-a1718072-633e-11e8-9f76-b2eeb0683d4c.png)

**Comment by jalbertsr** [comment]
what are we supposed to show? mobile design taking 100% of the width and centring everything? or maybe disallow landscape temporarily until we have landscape designs?

**Comment by kantord** [comment]
I suggest simply changing the breakpoints to the smallest possible value which is wide enough for the desktop design to fit. (I mean, the booking + the help bar.)

**Comment by jaroslav-kubicek** [comment]
I would suggest to remove also all `(min-width: 320px)` - it shouldn't we necessary, just saying _"everything up to this value"_ is fine

**Comment by kantord** [comment]
Agreed... Even if the screen is so small that the design breaks, it should break less than the desktop version :-D
