### ISSUE TITLE
RawSignIn, RawContact, etc... are confusing names

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#276]
I believe "raw" does not describe "email" very well. So I think these should be renamed `EmailSignIn`, `EmailContact`, etc...

**Comment by jaroslav-kubicek** [comment]
`RawSignIn, RawSignIn` => I don't get this...

**Comment by jalbertsr** [comment]
We continued in the direction of using `raw`, for example last PR merged: 
https://github.com/kiwicom/smart-faq/pull/629/files#diff-d4977062a27381d58a27ffcc294bae96R35 
So I think we can close this issue.
