### ISSUE TITLE
Make frontend server side rendering more efficient

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#287]
Load SmartFAQ asynchronously on frontend after clicking on "Help" button using `import()` function, so it's not processed during SSR

See: https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules

**Comment by git-toni** [comment]
After spending quite some time with this one, I couldn't figure out any difference when prefetching SmartFAQ at `src/common/modules/MainView/MainView` regarding the server-rendered first page. 
To my understanding of `frontend/frontend`(which is definitely lacking) the components are transpiled + built via babel+webpack and the resulting code is linked to the server-rendered HTML as a `src` tag. Hence the server-rendered part is not affected much by whether we pre-fetch smartFAQ or not.

However the JS code first downloaded by the user could be reduced if we dynamically import the module? That's another topic tho.

**Comment by jalbertsr** [comment]
Closed by issue in gitlab https://gitlab.skypicker.com/frontend/frontend/merge_requests/5489
