### ISSUE TITLE
Should we disable smart-faq based on device, not exclusively screen resolution?

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#297]
As raised in our [PR](https://gitlab.skypicker.com/frontend/frontend/merge_requests/4597#note_593865) for frontend integration, it seems strange that the client is able to use the smart-faq in their device when it's in landscape mode, but not in portrait mode - that can cause weird situations like you are looking at the old help, flip your phone and suddenly a new help app appears.

What is your opinion on this? @jaroslav-kubicek @jalbertsr @kantord @dinodsaurus @edgarordonez @mjancik  

Should we disable it based on `device` *and* `resolution` instead of just resolution. Apparently as of now the feature observed to determine the `isMobile` redux store attribute(which we use to render/not render)  is only screen resolution. https://gitlab.skypicker.com/frontend/frontend/blob/master/app/scripts/tools/windowBindings.js

**Comment by kantord** [comment]
I am not very comfortable with using device detection to implement responsive design. I think ideally the site should work the same way in small-sized browser windows as it works on mobile. (Well, with some exceptions maybe, but in our case I can't think of any)

**Comment by jaroslav-kubicek** [comment]
let's implement responsive designs and this issue will be automatically resolved as well 👼

**Comment by git-toni** [comment]
Aren't we intentionally limiting the userbase to desktop-only?

**Comment by kantord** [comment]
I think it's worth mentioning that this is only about the temporary desktop-only release, as @git-toni mentioned in an in-person discussion.

**Comment by git-toni** [comment]
So after discussion with @jaroslav-kubicek it seems we will actually deploy responsive designs as well for this first release so this issue can be closed.
