### ISSUE TITLE
Fix github pages deployment

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#302]
Apparently since we added `gh-pages` the deployments fail. It seems to be related to git user authentication. Possibly a lack of options params to `gh-pages` or ENV variables at CircleCI
https://circleci.com/gh/kiwicom/smart-faq/2804

**Comment by dinodsaurus** [comment]
uf I forgot about that, on it

**Comment by git-toni** [comment]
This one should help :slightly_smiling_face:  https://github.com/kiwicom/smart-faq/blob/809cfdbb792f8c6f2b7a4ef52e67335c2f930a5d/scripts/deploy-ghpages.sh#L18
