### ISSUE TITLE
Remove weird white block after feedback form gains the focus

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#305]
Video: http://recordit.co/y2dGb3jjn8

**Comment by jalbertsr** [comment]
this is caused by [grammarly chrome extension](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) injecting its own html 

more info/possible solution(?): https://stackoverflow.com/a/46777787/6334411
