### ISSUE TITLE
Create Kiwi login page 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#31]
Acceptance criteria:

- Page according to design: [Marvel App](https://marvelapp.com/7iihb90/screen/39285700), [Zepplin Desing](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aa6b8e18e193557a2446e22)

**Comment by MagdalenaAlmanova** [comment]
It looks perfect 💯

**Comment by michalsanger** [comment]
![image](https://media1.tenor.com/images/6f3d12f4c131b238a899fba152fadcc6/tenor.gif)
