### ISSUE TITLE
Do not show empty booking section "PAST" or "UPCOMING"

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#313]
If there are no relevant bookings, do not show "PAST"/"UPCOMING" header

<img width="353" alt="screen shot 2018-06-01 at 16 41 41" src="https://user-images.githubusercontent.com/2174629/40846751-c82f2420-65ba-11e8-87d8-535e0d19d6b2.png">

**Comment by mjancik** [comment]
Hi guys, just a quick question. You are planning to delete the entire section if there is nothing? Shouldn't we prepare rather a message: "There is no upcoming (past) booking." We might also put a link there to our search if there is no upcoming booking for searching for one.

**Comment by kantord** [comment]
Yes, currently the whole empty section is hidden. I see your point. That might be a better implementation, honestly, I'm not sure which one is better :-)
