### ISSUE TITLE
All links in FAQ article content open in new tab

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#314]
All links that are somewhere in the content of an FAQ article must be opened in new tab.

**Comment by dinodsaurus** [comment]
I tried to do this the proper way - https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer but I could not get it to work :(

**Comment by jalbertsr** [comment]
this issue is close by this pr https://github.com/kiwicom/smart-faq/pull/344
