### ISSUE TITLE
Implement exponea event logs

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#320]
Main site is using exponea to analyse some specific actions that the user performs for marketing purposes. It is using the [Infinario](https://gitlab.skypicker.com/frontend/frontend/blob/f24b9d6402ac8af9dc87ff23f44f782a7313f973/server/markup/scripts/infinario.js) scripts, that register those events in the in-house backend.

We should integrate this with smart-faq.

**Comment by jaroslav-kubicek** [comment]
How is it related to #319 ? Can we have one issue for analytics?

**Comment by jaroslav-kubicek** [comment]
> How is it related to #319 ? Can we have one issue for analytics?

cc @git-toni

**Comment by jaroslav-kubicek** [comment]
closing as duplicate of #319
