### ISSUE TITLE
Feedback/Contact us design change

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#327]
Q/A raised an issue with the confusing way on how can a user contact us or leave us feedback. We agreed and prepared a small tweak:
<img width="447" alt="screenshot 2018-06-04 14 52 15" src="https://user-images.githubusercontent.com/37365838/40918544-e397bea4-6806-11e8-89f5-18a8bd60ace7.png">
<img width="438" alt="screenshot 2018-06-04 14 52 35" src="https://user-images.githubusercontent.com/37365838/40918556-ee25df36-6806-11e8-99ab-d7eba4bf7f76.png">

We will just add the contact page link underneath the feedback box and change the copy accordingly.
New design and flow: [https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard?seid=5ade100048dab651bfafdbf0](url)

**Comment by dinodsaurus** [comment]
@mjancik you can check it out here - https://smartfaq-327-feedback-design-change.surge.sh/
The only problem is that we dont have `Roboto-Medium` in the project..

**Comment by mjancik** [comment]
All links (primary, secondary) use `Roboto-Medium` according to Orbit guidelines. If it is a problem you can use bold and it will change to orbit eventually.

**Comment by dinodsaurus** [comment]
We need to update `orbit-components` but I dont know what breaking changes will occur, so for now we will make it bold
