### ISSUE TITLE
Migrate away from Microsoft GitHub 

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#331]
UPDATE: joke turning into hot topic: https://techcrunch.com/2018/06/05/gitlabs-high-end-plans-are-now-free-for-open-source-projects-and-schools/?guccounter=1

**Comment by jalbertsr** [comment]
🤣

**Comment by git-toni** [comment]
![image](https://user-images.githubusercontent.com/2466887/40922348-442201ca-6812-11e8-8419-75f31c1619ca.png)

**Comment by MRTNKCR** [comment]
wtf guys

**Comment by vborszeki** [comment]
😭
