### ISSUE TITLE
Better error, loading and not found messages on mobile booking header

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#338]
See:
- https://github.com/kiwicom/smart-faq/pull/261/files/727d839bbd3891e0a5de114e0b301137ea73aaa1#diff-0623a081852e113047c6de403c90b336
- https://github.com/kiwicom/smart-faq/pull/261/files/727d839bbd3891e0a5de114e0b301137ea73aaa1#diff-0623a081852e113047c6de403c90b336

**Comment by jalbertsr** [comment]
We need designs for that @mjancik

**Comment by mjancik** [comment]
I will prepare designs, but I am struggling with understanding of what exactly? 😄

**Comment by kantord** [comment]
@mjancik 
![screen shot 2018-06-07 at 07 54 16-fullpage](https://user-images.githubusercontent.com/3704904/41080758-2f8c9532-6a28-11e8-93a9-22d55273f225.png)

Here you could say it could just be hidden, however sometimes the booking header loads faster than the FAQs.

**Comment by kantord** [comment]
Closed due to obsoleteness  https://github.com/kiwicom/smart-faq/issues/416#issuecomment-397576150
