### ISSUE TITLE
Booking background color needs to be 100% of the height

### ISSUE THREAD

**Issue by dinodsaurus** [kiwicom/smart-faq#341]
When you are on a booking and open FAQ detail, FAQ detail is bigger then the Booking container. so background of the current booking doesnt cover the whole area

![](https://www.dropbox.com/s/dy558zvlqa7feaj/Screenshot%202018-06-05%2011.46.41.png?raw=1)

**Comment by jalbertsr** [comment]
There should be 2 scrolls, one for faqs and the other for booking, if there is more content in one of them, the scroll will show up just for this part of the content, I think this is solved by this issue https://github.com/kiwicom/smart-faq/issues/296, that's the one you are solving here https://github.com/kiwicom/smart-faq/pull/301 and once resolved this shouldn't happen.

**Comment by dinodsaurus** [comment]
Oh, thats true @jalbertsr
