### ISSUE TITLE
Loading "after booking" screens

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#361]
Two big animated loaders on one screen don't look very good. To prevent this, first we should fix this: #360 

Afterwards I would like to create a basic skeleton page on the left.

Design: https://zpl.io/bzM0lWG

**Comment by kantord** [comment]
wow!  Off topic I guess, but the skeleton looks cool! Should we animate it? Like this: https://codepen.io/oslego/pen/XdvWmd Also I'm thinking :thinking: shouldn't we just replace all loaders with skeletons like this? That could also solve https://github.com/kiwicom/smart-faq/issues/338

**Comment by mjancik** [comment]
Animation of skeletons looks great. Awesome idea, it might help to perceive the time of loading for the user better. 

I would not replace all loaders with skeletons. I would still leave the faq loading with the plane.

**Comment by kantord** [comment]
Is there a separate issue for the skeletons?

**Comment by dinodsaurus** [comment]
I centered the loading spinner on #366 .
Regarding "skeleton" there is this cool library http://danilowoz.com/create-content-loader/

**Comment by kantord** [comment]
Cool!

The library is essentially SVG with a wrapper that adds styling and animation right? Looks nice, however, what if we need to create a skeleton loader that is responsive?

**Comment by dinodsaurus** [comment]
I think it should not be a problem making it responsive using js (not sure if you can do it with css)
