### ISSUE TITLE
Dots should only be shown for unordered list

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#365]

**Comment by jalbertsr** [comment]
pls be more descriptive, where is the issue?

**Comment by jalbertsr** [comment]
I guess you mean this 

![this](https://monosnap.com/file/mFX8WE1lh10KKLZT1lqBQMpfQo4V5c)

**Comment by kantord** [comment]
Yes, that :-) I was going to upload the image but I was distracted hahaha
