### ISSUE TITLE
in categories please get rid of the white cube 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#374]
from the QA google sheet line 26, 
![screenshot](https://d1ro8r1rbfn3jf.cloudfront.net/ms_147903/tBXj3vEvxRRi8ycDc107nFqHlMGtok/Easy%2Bbooking%2Bwith%2BKiwi.com%2B2018-06-01%2B14-08-56.png?Expires=1528474585&Signature=NIKCF6Lsgi79zPlK6I0aYbmwomCzaCjr3qttXbiWXtck4BJx-yU19pyBlqnlsx2xULP3j-HzBDzRN36HKKEnJgA9ggP9bmNPtEZfrrN6qAcY~vQrOvsAhwzJpzdraa0pOUnwDP~MRa0XPLAhdlWyN5gHe8OOTHNUzOaH6y~dSxoN73XWHhMcayD2Ya~UkFzAlvPLkrl2QiklDSdeAjtYdIKYhyeBf78yjokPf0Jugt49uU7fmTGfUv9-YQtTO0fAYkgUzfMZzkI-a~qIWKA69xbx5VEwFOrJ7e1P69li0Y02ic4s8KbjrXI1T1ZaCqF~ITAblJk~Gbe-TRHm2Naz8g__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by kantord** [comment]
link broken. Correct link (hope) [very long link](https://d1ro8r1rbfn3jf.cloudfront.net/ms_147903/tBXj3vEvxRRi8ycDc107nFqHlMGtok/Easy%2Bbooking%2Bwith%2BKiwi.com%2B2018-06-01%2B14-08-56.png?Expires=1528817110&Signature=ibyzxtZsRWFjBf5iW7b~pm91lHGdBnoQHO2FJCOwbuGmHq2MDUV2aBFxr5i9xKG0~juI93X1Q0hIiac~-e~yj0VkKH3DXy27IAGeWv2mfdy4IBqtEN2FTM0t~ZdyqbG7zozqmO5TLT5B2rX2SWWRdX6r9xUV-NreBCbLKwkGFEgxbAqoURGyv1gz7g-7~Oq82nFN8PQpboLOEWcF8oj-pOxxDJ-Q9QkYEbcZmraqFvMeMSKyvMbF8NeVpQUOOCsdWC5y5H-xggrEFA-yarWR7jDB82RBO70AdAtAIqufNEUPTtBHBrxAS0AHk-2TZV9yR-4zaTCjgoVXJvn~Zn87wA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by kantord** [comment]
might be similar to https://github.com/kiwicom/smart-faq/issues/402 but the other way around probs. Lemme take a look
