### ISSUE TITLE
Remove background scrolling

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#380]
https://monosnap.com/file/TJEUECGJXSSLAczD02NRtyCRoSI6J0

**Comment by kantord** [comment]
we should implement this https://jsfiddle.net/TroyAlford/4wrxq/1/

**Comment by kantord** [comment]
Merged on frontend repo https://gitlab.skypicker.com/frontend/frontend/merge_requests/5151

**Comment by kantord** [comment]
Merging this to frontend master separately

**Comment by MagdalenaAlmanova** [comment]
I think, that it is quite hard to test because in Smar faq demo I don't see the background. However, The background scrolling is still persistent in Chrome and Opera both last v. The grey background is moving.  Please @kantord check this again, I am not sure. Thanks

**Comment by jalbertsr** [comment]
Is working for me in gitlab staging, agree with @MagdalenaAlmanova this issue is hard to test in standalone app, we can move it to gitlab QA.

**Comment by MRTNKCR** [comment]
@jaroslav-kubicek @jalbertsr  hello, are you guys sure this has been fixed? because there is still background scrolling on both my desktop and mobile....
