### ISSUE TITLE
Change Booking in-between stops arrow to match design

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#382]
Current: 
![image](https://user-images.githubusercontent.com/2466887/41159947-80811862-6b2e-11e8-8a55-6fbd7cd1fdc1.png)

design: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5adf5b3e2f1dbdd37e781a89

![image](https://user-images.githubusercontent.com/2466887/41159969-912a7bfe-6b2e-11e8-9f63-35607e4a1f33.png)

Not sure if Orbit is ready for this?

**Comment by dinodsaurus** [comment]
should we just use `svg` image for this one?

**Comment by jalbertsr** [comment]
we can us `arrowUp` from orbit components and rotate it
