### ISSUE TITLE
Show previously displayed booking

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#383]
Acceptance criteria

- When I open SmartFAQ anywhere on the frontend, it shows the nearest booking
- When I open SmartFAQ in MMB in booking detail page, this specific booking is opened
- When I open SmartFAQ anywhere, MMB booking detail included, and select different booking from the allbookings page, then I close SmartFAQ and reopen it again no matter on which page of the frontend, SmartFAQ is smart enough to display booking previously selected by a user 

=> in other words, if the user intentionally selected one booking from the list, keep track of such selection so it opens the same booking later again, but don't implement such memoization for specific booking which was displayed just because the user was on MMB detail page, makes sense?

**Comment by MagdalenaAlmanova** [comment]
I am sorry, but I don't understand of the assignment of this issue. :(  @kantord

**Comment by jalbertsr** [comment]
This can't be tested in the standalone app, we'll test when opening the MR in gitlab.
