### ISSUE TITLE
it is possible to submit an empty feedback form

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#384]
Acceptance criteria

- it's not possible to send  empty feedback form
- Should the button be disabled until you fill in the form?

http://recordit.co/NWz4uRPcQe

**Comment by git-toni** [comment]
Fixed this morning via https://github.com/kiwicom/smart-faq/pull/378

**Comment by git-toni** [comment]
Although button criteria is not met :smile:

**Comment by jalbertsr** [comment]
can we close this then?

**Comment by git-toni** [comment]
cc @jaroslav-kubicek

**Comment by jalbertsr** [comment]
closing since now we have design for that in a new issue, see https://github.com/kiwicom/smart-faq/issues/411
