### ISSUE TITLE
Remove double scroll still present in the Paying page of kiwicom

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#389]
Happens only when there's a wholepage scroll at kiwicom such as in the paying page.

![image](https://user-images.githubusercontent.com/2466887/41167626-c63d1b48-6b43-11e8-87ed-fe2e4284ff6f.png)

**Comment by dinodsaurus** [comment]
Should we disable `window` scroll as soon as our app is open?

**Comment by jalbertsr** [comment]
this issue was fixed in https://github.com/kiwicom/smart-faq/issues/380
