### ISSUE TITLE
direct link to contact us is not showing on mobile 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#398]
direct link to contact us is not showing on mobile  in the articles compared to how it should show on desktop

https://monosnap.com/file/EDrvCLtR5gYCHOph6Qy74fMNMfUjE0

**Comment by kantord** [comment]
Probably solved by https://github.com/kiwicom/smart-faq/pull/404

**Comment by kantord** [comment]
Possibly duplicate of #402

**Comment by jaroslav-kubicek** [comment]
so I guess it can be closed, right? 🙂

**Comment by kantord** [comment]
![2018-06-21-153512_1025x1546_scrot](https://user-images.githubusercontent.com/3704904/41722458-ed372c3c-7568-11e8-81b6-41df0c3b6daf.png)
Will be fixed by https://github.com/kiwicom/smart-faq/pull/466
