### ISSUE TITLE
Low usability for landscape iPhone

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#401]
- I can't close the help in landscape
- scrolling is difficult
- only part of the screen is scrollable, see below:

![img_5031](https://user-images.githubusercontent.com/2174629/41233645-59bf01cc-6d8a-11e8-8e35-65928dd21b4d.jpg)

Video: https://monosnap.com/file/JudyZMoHMKCBddfe64uHMxRC7NMNaP

**Comment by kantord** [comment]
we should revise this after https://github.com/kiwicom/smart-faq/pull/404 is merged

**Comment by kantord** [comment]
related: https://github.com/kiwicom/smart-faq/issues/405

**Comment by mjancik** [comment]
So the new designs for mobile landscape: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard?seid=5b1fd052e02db4652256c1da

while scrolling it should hide the header: https://zpl.io/25qNRWe

**Comment by kantord** [comment]
After taking another look, I think the :x: button here is a bit confusing
https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5b1fd04e65ca1be0450748be

It looks as if it was for clearing the search term in the box, whereas it should close the search itself if I understand correctly. I think there should be a back button or something

**Comment by kantord** [comment]
Closing this because my phone, after merging https://github.com/kiwicom/smart-faq/pull/466 all of this works, so it seems to be fixed. Besides https://github.com/kiwicom/smart-faq/issues/449 seems to be a superset of this issue.
