### ISSUE TITLE
"contact us" unreachable on iPad with longer article

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#402]
on IPad, i have problems scrolling to the bottom of longer articles where contact us link is. the page keeps cropping it out of the frame

Video: https://monosnap.com/file/XTOJjJlxQnehOcfgGYxAPRZ1o3m2mK
same issue for iPhone: https://monosnap.com/file/EDrvCLtR5gYCHOph6Qy74fMNMfUjE0

**Comment by kantord** [comment]
Apparently the issue is caused by scrollableContent being oversized. I'll implement a fix by finding a way to properly size it :-)

**Comment by kantord** [comment]
Note regarding the issue itself: expanding the mobile booking header makes the issue worse by pushing even more content out.
