### ISSUE TITLE
Very little space for actual content on iPhone landscape

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#405]
![2018-06-11-165901_1497x869_scrot](https://user-images.githubusercontent.com/3704904/41239633-ed1bc1b8-6d98-11e8-913f-9d11f4b69235.png)

More than half of the screen is being occupied by elements you cannot scroll away.

**Comment by mjancik** [comment]
Preparing designs for it...

**Comment by mjancik** [comment]
So the new designs for mobile landscape: https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard?seid=5b1fd052e02db4652256c1da

while scrolling it should hide the header: https://zpl.io/25qNRWe

**Comment by kantord** [comment]
Cool! Thanks

**Comment by jalbertsr** [comment]
there are new designs for that, closing issue.
