### ISSUE TITLE
Long perex causes the entire mobile layout to break

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#410]
![2018-06-12-090737_789x1292_scrot](https://user-images.githubusercontent.com/3704904/41275147-3b9ee798-6e20-11e8-8df1-63a047ef7176.png)

**Comment by jalbertsr** [comment]
is working fine for me 🤷‍♂️
![screenshot](https://i.gyazo.com/73d38bd8b3c45ad06a94ebadbc8b818f.png)

**Comment by kantord** [comment]
Matter of fact I cannot reproduce it anymore myself... :man_shrugging:

I'll re-open the issue if I can reproduce it somehow
