### ISSUE TITLE
On mobile change the calculation for content height

### ISSUE THREAD

**Issue by dinodsaurus** [kiwicom/smart-faq#412]
Mobile header height is `123px` so we need to adjust the calculation 
![ContentImg](https://www.dropbox.com/s/to452t9sio1fahq/Screenshot%202018-06-12%2011.26.09.png?raw=1)

**Comment by kantord** [comment]
Imho we should not have to specify the header height. Actually, the header height can even change when you expand the booking detail. So we have at least 3 different header heights, and more are possibly coming up

**Comment by kantord** [comment]
This is also related https://github.com/kiwicom/smart-faq/issues/402

**Comment by dinodsaurus** [comment]
Thats true, then I would say the best solution would be to rewrite it to flexbox. What do you think?

**Comment by kantord** [comment]
Yup, I’m working on exactly that for #402. The issue goes beyond this one CSS rule, for example ScrollableContent uses a hard coded  vh to set height.

**Comment by kantord** [comment]
I think there are a bunch of issues related now to height sizing on mobile haha 😆 all because of the booking header

**Comment by dinodsaurus** [comment]
gl 🤣
