### ISSUE TITLE
Set error boundaries for SmartFAQ

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#415]
- Wrap the main App component in error boundary so we don't crash the whole frontend in case of render failure.
- Show error message if something went wrong.

More info: https://reactjs.org/docs/error-boundaries.html
Zeplin: https://zpl.io/aNpXrAZ

**Comment by dinodsaurus** [comment]
Should we also have some `Sentry` call in this function? Dunno if `Sentry` catches everything automatically.. @git-toni

**Comment by jaroslav-kubicek** [comment]
> Also Im not sure if this design is good enough because error can also happen on the Booking part of the screen.

What do you mean? the whole `App` should be wrapped, booking parts included

**Comment by dinodsaurus** [comment]
Im just talking about the design, In the designs error shows on the "FAQ" part of the screen, so it could look a bit funky if the "Booking" part is white with no content in it.

**Comment by dinodsaurus** [comment]
This is what I did in #422 😉
