### ISSUE TITLE
It's still possible to write into search field with displayed SmartFAQs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#417]
When SmartFAQ input loses focus, it's possible to fill-in search form in the background.

Video: http://recordit.co/NNk1C0Qe0e

**Comment by kantord** [comment]
Bug or feature? :joy:

**Comment by kantord** [comment]
Closed by https://gitlab.skypicker.com/frontend/frontend/merge_requests/5171/diffs

**Comment by kantord** [comment]
I have serious doubts that this can be solved to perfection without a major revamp of how forms work in FE. I'd say this potentially has a higher cost to implement than the benefit we get from implementing this, and it's definitely not our lowest hanging fruit in keyboard usability.

**Comment by jaroslav-kubicek** [comment]
I believe it can be solved quite fairly, it just didn't have the highest priority now :)

**Comment by MagdalenaAlmanova** [comment]
Hmm.. I think, that I could not test the issue..

**Comment by vborszeki** [comment]
@MagdalenaAlmanova yes, you’re right, it’s not possible to test in the standalone app
