### ISSUE TITLE
Disable/Enable screens based on Login status

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#43]
Some screens should obviously not be displayed if the user is logged in and vice-versa. We need to (de)authorize some screens to the user depending on whether they are logged in or not.

*Note: this description is unfinished and meant to kick-starter the discussion on the issue :)*

**User Logged-out screens**
- Sign In page
- Kiwicom Login
- Intro Page
- Social Sign in
-  FAQ root

**User Logged-IN screens**
- Intro Page
-  FAQ root

**Comment by git-toni** [comment]
@MRTNKCR  :)

**Comment by MRTNKCR** [comment]
@git-toni : Here is the response from UX team:

Based on the prototype https://marvelapp.com/7iihb90/screen/39265560
**Screens visible when logged out** 
- Intro (1/27)
- Help 1-0-0 (2/27)
- Help Sign in 1-1-0 (3/27)
- Help account (4/27)
- Help account - Forgotten password (1-1-2-1) (23/27)
- Help account - Forgotten password 2 (1-1-2-1) (24/27)
- Help account - Forgotten password 3 (1-1-2-2) (26/27)
- Help account - Forgotten password 4 (1-1-2-2) (27/27)
- Check email (5/27)
- Help (1b-1-0) (9/27)
- Help (1b-2a-1) (8/27)
- Help (1b-2a-0) (7/27)
- Help (1b-2a-2) (6/27)
- Help search (1b-2b-0) (20/27)
- Help article (22/27)

**Screens visible when logged in:**
- Intro (1/27)
- Help normal (2-1a-0) (10, 25/27)
- Help normal (2-1a-1) (16/27)
- Help normal flight expand (2-1a-1) (21/27)
- Help normal (2-1a-2) (15/27)
- Help article (1d-1a-0) (11, 17/27)
- Help urgent (12/27)
- Help search (13/27)
- Help search (2-2a-0) (18/27)
- Select other booking (19/27)

**Comment by MagdalenaAlmanova** [comment]
👍
