### ISSUE TITLE
Refactor integration tests: make Login process into a Cypress.command

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#433]
The login process appears in more than one test. It seems useful to have it as a separate cypress command. Eg. https://docs.cypress.io/api/cypress-api/custom-commands.html#Custom-login-command

**Comment by dinodsaurus** [comment]
Not sure if we can do that @git-toni  because we are storing stuff inside of `index.js`
https://github.com/kiwicom/smart-faq/blob/master/src/index.js#L63

**Comment by git-toni** [comment]
Agree! However what about moving the login flow via browser to a Cypress.command. ie. mimicking the "click on login" flow via the UI?

**Comment by dinodsaurus** [comment]
Yep, that makes sense 👍

**Comment by vborszeki** [comment]
I have implemented it in #597
