### ISSUE TITLE
Responsive layout is still broken on mobile

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#449]
Issues to solve:

- [x] hidden FAQ categories
~- [ ] two scrolls on mobile landscape~
- [x] login & intro screens not responsive - not taking the full width on mobile device
- [x] intro & login screens on mobile landscape are centered, designs: https://zpl.io/agv9rJN and https://zpl.io/2EAwe3D

![img_5063](https://user-images.githubusercontent.com/2174629/41598110-92dfa22c-73cf-11e8-80f5-d458762d6469.jpg)
![img_5065](https://user-images.githubusercontent.com/2174629/41598112-93130a5e-73cf-11e8-9890-774c35ab4d67.jpg)
![img_5064](https://user-images.githubusercontent.com/2174629/41598113-936a71d6-73cf-11e8-8878-1f35c0847de8.jpg)

**Comment by kantord** [comment]
>  - [ ] hidden FAQ categories
> - [ ] two scrolls on mobile landscape

These two should be fixed after rebasing

**Comment by jaroslav-kubicek** [comment]
>  - [ ]  two scrolls on mobile landscape

nope, still present

**Comment by kantord** [comment]
:confused:

**Comment by MagdalenaAlmanova** [comment]
The first two points are fixed :) 

About the third point, I am not sure. If I should test on www.kiwicom.github.io,  intro and login screens on the mobile landscape are not centered. See screenshots. 
![img_9459](https://user-images.githubusercontent.com/37298895/41998823-fae41776-7a5b-11e8-94e2-3bcfbc62c752.PNG)
![img_9460](https://user-images.githubusercontent.com/37298895/41999012-8407a1a8-7a5c-11e8-9ca5-1658adc59520.PNG)


If I should test on www.smartfaq-fix-issue-402.surge.sh, there were some mistakes: on the login page: The text wasn't  "sign in" centralized, "I want to use my kiwi.com account should have been bold and there shouldn't be the text "We need you to sign in to provide...." On the kiwi.com account page, the headline isn't centralized and there is text missing "If you have..." See on screenshots. 
Demo v.
![img_9462](https://user-images.githubusercontent.com/37298895/41999024-8f0a1dc4-7a5c-11e8-9e5c-22b99af1308b.PNG)
Prototype v.
![screen shot 2018-06-27 at 22 38 06](https://user-images.githubusercontent.com/37298895/41999035-9d83346c-7a5c-11e8-93e2-5e50a9141657.png)

Demo v.
![img_9461](https://user-images.githubusercontent.com/37298895/41999047-a81ad452-7a5c-11e8-9730-f01be9413e73.PNG)
Prototype v.
![screen shot 2018-06-27 at 22 37 54](https://user-images.githubusercontent.com/37298895/41999053-ae62d2c4-7a5c-11e8-978b-396089b09c50.png)

I will wait for the answer and then I can move to the right column :) 

Thanks

**Comment by jaroslav-kubicek** [comment]
https://kiwicom.github.io/smart-faq/ redeployed, now the changes are there (Previous automatic build failed), cc @MagdalenaAlmanova

**Comment by vborszeki** [comment]
> I will wait for the answer and then I can move to the right column :)

I have discussed these design issues with @mjancik and the screens will be changed slightly, so you can move it back @MagdalenaAlmanova

**Comment by MagdalenaAlmanova** [comment]
I found only "facelift" bug: Google and FB button should be better centralized (the text into buttons).
Demo v.
![img_9501](https://user-images.githubusercontent.com/37298895/42138625-b9cbb780-7d80-11e8-9e5d-e794bb7fd5f8.PNG)
![img_9502](https://user-images.githubusercontent.com/37298895/42138627-bf170a3c-7d80-11e8-93d8-d2be704f7831.PNG)
Prototype v.
![screen shot 2018-07-01 at 22 38 47](https://user-images.githubusercontent.com/37298895/42138630-d1cdd1ec-7d80-11e8-81d5-2ba5af19c33f.png)
 
About the hidden FAQ categories, I don't understand, what is a meaning of this point. And is it correct, when faq categories look as? (no spaces between faq categories?)
![img_9503](https://user-images.githubusercontent.com/37298895/42138754-b3675a78-7d82-11e8-929d-a51a59949bfb.PNG)

 Thanks for your answer :)

**Comment by MRTNKCR** [comment]
I think we should move this issue back to `in progress` if is some dev work needed. Thank you @MagdalenaAlmanova

**Comment by vborszeki** [comment]
This is how the buttons in our design system work. I wouldn't force them to alter from the original appearance. @MRTNKCR @MagdalenaAlmanova

**Comment by MRTNKCR** [comment]
Ok, we dicussed with @vborszeki and we can release this issue nad fix the "hidden categories" later. Can you please start a new issue for that @MagdalenaAlmanova ? I'm moving this issue to DONE. Thank you.
