### ISSUE TITLE
Implement animations

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#45]
As [designed](https://paper.dropbox.com/doc/Smart-FAQ-animations-Qw0jXO5uTBFKy5xp8jeA1) by Martin  we should implement animations in the component.

So far animations are in these parts:
- Screen transitions -> slides
- On hover some elements -> change shadow.

Approaches/suggestions up for discussion :) 
- Native CSS for hover shadow changes, via `:hover` in our styled components.
- `ReactCSSTransitionGroup`  or `react-motion` or something JS-based for page sliding.

**Comment by mjancik** [comment]
As we discussed:
Since there is quite a loading time between the different categories it would be overwhelming to mix loading animation and transition animation together. We decided not to implement any transition as of now.
