### ISSUE TITLE
Ordering of upcoming bookings is different then on MMB

### ISSUE THREAD

**Issue by dinodsaurus** [kiwicom/smart-faq#450]
The ordering is different, in `smart-faq` the closest departure date is first but on MMB the `newest` or something like that is first..
But I think our implementation is ok, the one that needs fixing is `frontend`. What do you think? @jaroslav-kubicek @git-toni @jalbertsr 
![](https://www.dropbox.com/s/k7axhzxe4mfdx3z/Screenshot%202018-06-19%2017.00.51.png?raw=1)

**Comment by jalbertsr** [comment]
@Strajk will answer

**Comment by Strajk** [comment]
I just checked

On FE, bookings were sorted by booking date DESC in the past, but since 
https://gitlab.skypicker.com/booking/backend/merge_requests/3190 there are sorted by **departure of first segment**

Your solution makes more sense for upcoming trips, will discuss with our designer

**Comment by Strajk** [comment]
@dinodsaurus we will discuss it here https://gitlab.skypicker.com/kiwi/coop/issues/52
