### ISSUE TITLE
Add boarding pass info

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#454]
Acceptance criteria

- [x] When clicking on the boarding pass, specific FAQ category is shown
- [x] Info about the availability of boarding pass is shown
- [ ] Show tooltip for boarding pass at the airport  https://zpl.io/25qwg9J

Note GraphQL server will need to be updated to provide such info.

<img width="601" alt="screen shot 2018-06-20 at 12 06 52" src="https://user-images.githubusercontent.com/2174629/41652156-9a4ea20c-7482-11e8-9cfa-0c58fe59f898.png">

Zeplin: https://zpl.io/beYLgOP

**Comment by kantord** [comment]
Today I've been working to have a PR on graphql merged that can simplify it. I hope to meet the acceptance criteria today, so as stated in my standup it might be finished today. I'd like to spend some time refactoring this as there is a lot of code duplication introduced here, but that might be done in a separate issue so that this can go through QA in the meantime

**Comment by MRTNKCR** [comment]
Thanks, that sounds good. I would be great to have this pushed through to QA and prod this week, we can focus on the improvements later.

**Comment by kantord** [comment]
Well, it might not pass the code review with this much code duplication. (If there will be anyone available to review it, that is :smile: )

**Comment by kantord** [comment]
The graphql stuff I did were merged, so I pushed a new commit that displays the flights and their boarding passes.

Notes:
- the data about availability in terms of time left/free pickup at airport is not even in graphql yet. This might not be trivial
- to my best knowledge, we don't even have a tooltip component yet, so that will have to be implemented too

So even though the list is working and boarding passes can be downloaded, implementing all the details on the designs perfectly might take more time.

**Comment by MagdalenaAlmanova** [comment]
I found some bugs:

1. The text "boarding pass" should be better centralized on the icon of the boarding pass, I think...
Demo v.
![screen shot 2018-07-08 at 21 40 10](https://user-images.githubusercontent.com/37298895/42423311-9ec0ceda-82f8-11e8-8cd2-93e4fc1b1000.png)
![screen shot 2018-07-08 at 21 40 15](https://user-images.githubusercontent.com/37298895/42423313-a316e320-82f8-11e8-97fa-b18eeea40b37.png)
Prototype v.
![screen shot 2018-07-08 at 21 39 47](https://user-images.githubusercontent.com/37298895/42423316-b1ac8534-82f8-11e8-8f17-92382d6b55ed.png)
![screen shot 2018-07-08 at 21 39 59](https://user-images.githubusercontent.com/37298895/42423321-b51e63b8-82f8-11e8-96cf-1f957776039f.png)

2. The text "Here, you can download your ...." should be divided and I am not sure but shouldn't be there a dot? In the "baggage" there is one and in the "boarding pass" isn't? 
demo v.
![screen shot 2018-07-08 at 21 40 23](https://user-images.githubusercontent.com/37298895/42423372-596d7562-82f9-11e8-9716-def6a546b901.png)
Prototype v. 
![screen shot 2018-07-08 at 21 55 46](https://user-images.githubusercontent.com/37298895/42423391-b6f960b0-82f9-11e8-93c4-ad746ed60c1e.png)

3. Destinations aren't bold in Opera and Chrome (last v.)
![screen shot 2018-07-08 at 21 43 18](https://user-images.githubusercontent.com/37298895/42423416-f29e28ee-82f9-11e8-9189-a66a2b50d16c.png)

4. The same problem as in the "baggage" issue. When I click on "baggage" or "boarding pass" it shows me baggage or boarding passes, but when I "unclicked" "baggage" or "boarding pass" it shows me nothing. I think that it should show FAQ categories.
![screen shot 2018-07-08 at 21 36 05](https://user-images.githubusercontent.com/37298895/42423430-4e839b8a-82fa-11e8-9a43-42d89120bf71.png)

**Comment by MRTNKCR** [comment]
@mjancik what should happen when the user "unclicks" the button?

**Comment by mjancik** [comment]
1. The BP/Baggage buttons are orbit link buttons. (except that they stay "focused")
2. Yes there should be a full stop after the description.
4. After un-clicking it should return to home screen.

**Comment by kantord** [comment]
@mjancik thanks for the info. One more: what should happen if the user navigates away from the category but doesn't un-click the baggage/boarding pass button?

**Comment by mjancik** [comment]
Also un-focus the button :)

**Comment by kantord** [comment]
It seems that it's not possible to force an orbit button to stay "pressed". So we might have to stick with the custom implementation for now. Is that OK for the MVP?

**Comment by mjancik** [comment]
I was afraid of that. Yes, we can leave it custom. Until either I or Orbit guys can come up with a solution.

**Comment by MagdalenaAlmanova** [comment]
👍
