### ISSUE TITLE
Two back buttons

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#462]
The user shouldn't see two back buttons at once. The bottom one is only for after booking interface.
https://www.dropbox.com/s/xly4rvt8rz3nn37/Screenshot%202018-06-20%2023.57.25.png?dl=0

**Comment by jalbertsr** [comment]
is this issue still persistent? or can we close it?

**Comment by mjancik** [comment]
No idea how to recreate it, so I guess we can close it.
