### ISSUE TITLE
Track click on AskUs and GoBack

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#463]
A few events still left to track, these two could perfectly go together :slightly_smiling_face: 

- Whenever someone clicks on "Ask Us" feedback button.
```
eventName: "smartFAQCategories"
attributes: {
  action: "clickOnAskUs"
}
```

- Whenever someone clicks on "Go back"(I Imagine it's related to breadcrumbs as well. ?
```
eventName: "goBack"
attributes: {
  action: "buttonClick"
  // maybe some status info here?(eg. what was search - if anything-, going back from which article, etc)
}
```

We should clarify the GoBack event a bit.

**Comment by jalbertsr** [comment]
closing in favour of https://github.com/kiwicom/smart-faq/issues/637
