### ISSUE TITLE
Refactor routing 

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#468]
Acceptance criteria:

- [x] Replace Memory router by custom router that will update `?help` query param on every route change, so you can always forward up-to-date link to specific article

How to test:

- as you navigate through the app, `?help` param in url should be in sync with your current position in the application, back / forward browser buttons should still work & after a full page refresh, the exact same page in the page should be loaded

**Comment by MagdalenaAlmanova** [comment]
Perfect 💯
