### ISSUE TITLE
Cypress test depends on content in knowledgebase

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#471]
See this hotfix pull request:
https://github.com/kiwicom/smart-faq/pull/470

The cypress test in question failed because the title of the article was changed in knowledgebase. The hotfix fixes the issue, however it might be a good idea to replace this assertion with something that cannot be broken by changes outside that are not in the codebase.

**Comment by dinodsaurus** [comment]
We discussed this and came to a conclusion that this is ok because seeing the faq article is the most important thing in our app and hardcoding it should be ok for now.. they are not supposed to change that often and if they do we will change it 😊

**Comment by jaroslav-kubicek** [comment]
Yes, as Dino said. If that happens more often than we though, we will reopen this.

**Comment by kantord** [comment]
:+1:

**Comment by kantord** [comment]
@vborszeki ran into this today. 1 hour later I did, too

**Comment by dinodsaurus** [comment]
ok, then just check if it exists ;)
