### ISSUE TITLE
UI fix: fix the alignment of the header title for anonymous user

### ISSUE THREAD

**Issue by vborszeki** [kiwicom/smart-faq#473]
The title should be centered

<img width="651" alt="screen shot 2018-06-21 at 16 11 18" src="https://user-images.githubusercontent.com/18072606/41724416-cb069a44-756d-11e8-9855-1d540bab5db6.png">

**Comment by kantord** [comment]
Isn't this a duplicate of https://github.com/kiwicom/smart-faq/pull/472?

**Comment by vborszeki** [comment]
Yes it is, I have just realised, that it has been already implemented, so I am closing this issue
