### ISSUE TITLE
Use semantic-release to automate the npm publication process

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#474]
see https://skypicker.slack.com/archives/C9K87QN6Q/p1529590764000002

**Comment by kantord** [comment]
@jaroslav-kubicek plz https://glebbahmutov.com/blog/how-to-setup-semantic-release-on-circle-ci/

I believe I don't have authorization to do that alone :-)

**Comment by jaroslav-kubicek** [comment]
> I believe I don't have authorization to do that alone :-)

you can ask on slack for membership in kiwicom github organization 🙂
