### ISSUE TITLE
Download e-ticket/ layout change

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#486]
Adding possibility to download e-ticket. There is a slight change of the layout to be aligned to the left.
![screenshot 2018-06-25 16 19 10](https://user-images.githubusercontent.com/37365838/41855701-92daf826-7893-11e8-92df-d5b39ea6a34f.png)

Behaviour: When clicking the link it will open/download the PDF file.
Design: https://zpl.io/beYLgOP

**Comment by MagdalenaAlmanova** [comment]
It is really user friendly option :)

**Comment by MRTNKCR** [comment]
Can we please merge this to an npm package and push it to the production asap?

**Comment by MRTNKCR** [comment]
Why is it waiting here for 6 days???

**Comment by kantord** [comment]
Sure I can do it

**Comment by MRTNKCR** [comment]
@kantord thank you 👍
