### ISSUE TITLE
Make Legs expandable

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#487]
Acceptance criteria:
- arrows on right
- additional info is shown upon expanding the leg

- IMPORTANT: we are only adding the expanding fuctionality, the complete additional info will be covered in https://github.com/kiwicom/smart-faq/issues/513

![screen shot 2018-06-25 at 16 54 37](https://user-images.githubusercontent.com/2174629/41857742-8267dc8e-7898-11e8-8cae-c4e349c43257.png)

When expanded:

![screen shot 2018-06-27 at 17 21 57](https://user-images.githubusercontent.com/2174629/41983536-af266dd4-7a2e-11e8-8a5a-2b62d01a20c6.png)

Storybook on FE: https://bit.ly/2Kjxmcy

**Comment by MRTNKCR** [comment]
I added two new issues for the additional info - see links above ⬆️
