### ISSUE TITLE
Refactor Login button

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#488]
- Use Button from orbit
- add loading indicator when login mutation is being executed

![screen shot 2018-06-25 at 16 56 41](https://user-images.githubusercontent.com/2174629/41857997-11aa2186-7899-11e8-801e-c569682284da.png)

**Comment by MagdalenaAlmanova** [comment]
I think that The font thickness of "sign in" can be little thinner or color can be little brighter. 
Demo v. 
![screen shot 2018-06-28 at 22 22 09](https://user-images.githubusercontent.com/37298895/42058901-1c29f22c-7b22-11e8-9c81-ae304fb89d90.png)
Prototype v.
![screen shot 2018-06-28 at 22 22 20](https://user-images.githubusercontent.com/37298895/42058919-2682057a-7b22-11e8-9ba5-c99ba9940008.png)

If not, just moved this issue to "Done" collum, please. Thanks :)
