### ISSUE TITLE
When user logs in via token in MMB, he isn't logged into SmartFAQ

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#489]
Video: https://monosnap.com/file/JVnQ3kk46pbaFZjWNwuc4dHGSzUnHF

**Comment by kantord** [comment]
What does this actually mean? What is "when user logs in via token? It's not shown in the video. The issue cannot be reproduced without this information, because with regular login it just works.

**Comment by jalbertsr** [comment]
@kantord You can receive an email that automatically logs you in to MMB through a token

**Comment by kantord** [comment]
ah ok, it's that then! But how do I receive this email?

**Comment by jalbertsr** [comment]
I investigated and I have a link example `https://www.kiwi.com/en/manage/6857328/privateToken` if you need the whole link with token to test/try pls ask me in slack
