### ISSUE TITLE
Replace bookingId with node { id }

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#491]
bookingId is deprecated :-)

**Comment by jaroslav-kubicek** [comment]
I hear you...

...but these thoughts are forbidden 🤐 

of course, we know the inner implementation of ID field, but we should act as if it's completely opaque for us. Also, you would need to know whether it's `BookingOneWay`, `BookingReturn` or `BookingMulticity`

**Comment by jaroslav-kubicek** [comment]
so if you allow such a move, I'm going to close this for now 👼
