### ISSUE TITLE
Fix scroll in FAQs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#496]
Related to #449 

- There are still two scrolls in mobile landscape view

![41598112-93130a5e-73cf-11e8-9890-774c35ab4d67](https://user-images.githubusercontent.com/2174629/41969069-94d88a02-7a06-11e8-89fb-31f916c20db2.jpg)

- There is a discrepancy between FAQ article detail and FAQ category list - breadcrumbs in the article are scrollable, as opposed to list of categories.

![screen shot 2018-06-27 at 12 04 10](https://user-images.githubusercontent.com/2174629/41969012-6a6eadbe-7a06-11e8-8d93-8146e40651ab.png)
![screen shot 2018-06-27 at 12 03 54](https://user-images.githubusercontent.com/2174629/41969013-6a980be6-7a06-11e8-9db3-73a9eab490af.png)

**Comment by vborszeki** [comment]
with the new header, there is no breadcrumb for the FAQ category list, so this issue is obsolete
