### ISSUE TITLE
Add cypress tests verifying booking flow in mobile layout

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#510]
Add cypress tests that will verify that:

A user can log in to see booking info
Can expand the info
Select another booking

**Comment by MagdalenaAlmanova** [comment]
I think, that I cannot test this issue, but I tested it and login via kiwi.com account working and also select another booking.

**Comment by kantord** [comment]
@MagdalenaAlmanova yes, you don't need to test this one :-) Thanks. I thought we put it in Done directly, sorry for leaving it in QA
