### ISSUE TITLE
Additional info: Make legs expandable [GraphQL]

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#514]
Based on this issue: https://github.com/kiwicom/smart-faq/issues/487

The expandable functionality has been merged, now we need to add the additional info. This particular issue is covering the backend (GraphQL) part.

Acceptance criteria:

arrows on right
additional info is shown upon expanding the leg
![41983536-af266dd4-7a2e-11e8-8a5a-2b62d01a20c6](https://user-images.githubusercontent.com/7661448/42225160-2785e8ca-7edc-11e8-8b32-b4e0de75c9c4.png)

When expanded:
![41857742-8267dc8e-7898-11e8-8cae-c4e349c43257](https://user-images.githubusercontent.com/7661448/42225174-2ea263c2-7edc-11e8-863e-fe4cb70fbe33.png)

Storybook on FE: https://bit.ly/2Kjxmcy

**Comment by MRTNKCR** [comment]
Ok, I agree with @vborszeki to move this issue to the GraphQL repo. Will be moved and closed shortly.

**Comment by vborszeki** [comment]
Additional info for flights were added to GraphQL in https://github.com/kiwicom/graphql/pull/257
