### ISSUE TITLE
Fix separation lines for Boarding Passes and Baggage Info

### ISSUE THREAD

**Issue by vborszeki** [kiwicom/smart-faq#522]
The separation line's height should be 1px.

<img width="564" alt="screen shot 2018-07-05 at 11 13 53" src="https://user-images.githubusercontent.com/18072606/42314588-a65366cc-8045-11e8-8654-db9bb05df139.png">

There should be a separation line between the title and the loader.

<img width="563" alt="screen shot 2018-07-05 at 11 14 33" src="https://user-images.githubusercontent.com/18072606/42314591-a86d8140-8045-11e8-94f7-369923b8d4b7.png">

**Comment by MagdalenaAlmanova** [comment]
Very good, I didn't notice the line is missing :)
