### ISSUE TITLE
Fix disappearing FAQs on toggling back the 'Baggage' and 'Boarding Pass' buttons

### ISSUE THREAD

**Issue by vborszeki** [kiwicom/smart-faq#524]
Toggling the 'Baggage' and 'Boarding Pass' buttons should not remove the FAQs list.

On clicking the 'Baggage' button, FAQs are shown below the Baggage info:

<img width="1170" alt="screen shot 2018-07-05 at 14 11 34" src="https://user-images.githubusercontent.com/18072606/42322623-80994844-805d-11e8-926b-3d81755a3e19.png">

After clicking it again, the FAQs dissappear, which is not the expected behavior:

<img width="1141" alt="screen shot 2018-07-05 at 14 12 24" src="https://user-images.githubusercontent.com/18072606/42322624-8130f6ee-805d-11e8-833f-b5f85bb39707.png">

**Comment by vborszeki** [comment]
#527 fixes this issue

**Comment by MagdalenaAlmanova** [comment]
I tested it but on the link, https://kiwicom.github.io/smart-faq/ is it still persistent. @vborszeki 

![screen shot 2018-07-09 at 13 53 07](https://user-images.githubusercontent.com/37298895/42449599-917586ec-8381-11e8-91f7-42b8269dbc2c.png)

**Comment by jalbertsr** [comment]
@MagdalenaAlmanova is ok we hide it on prupose, we'll do a first release without baggage button until we are sure the info in the baggage card is 100% correct.
