### ISSUE TITLE
Fetching list of FAQs based on status of the booking does not work when Baggage button is active

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#528]
When a session ends with the Booking button active, the status-based fetching of the FAQs does not work properly.

As @MagdalenaAlmanova reported: When the session on smart FAQ ends and I sign in again, it shows nothing in baggage but the button of baggage or boarding pass is activated {It stayed activated on the last login session}.

The FAQs section displays all the structures (pre-booking, after-booking, after-trip...) in this case.

![42384409-31814aa8-813a-11e8-9707-df0049e733eb](https://user-images.githubusercontent.com/7661448/42447725-25340ff4-837b-11e8-96fa-993d1035cc5e.png)

![42384416-3586e158-813a-11e8-8ae1-32b07a3f0c9a](https://user-images.githubusercontent.com/7661448/42447724-25051834-837b-11e8-940c-839cab562a7a.png)

**Comment by kantord** [comment]
Is it possible that in some cases, there would be no available FAQ/Category when clicking the button?

**Comment by MRTNKCR** [comment]
I don't think so. The user should alway be redirected to "Home" when he signs in.

**Comment by MRTNKCR** [comment]
Or which button you mean? :-D

**Comment by kantord** [comment]
Baggage/Boarding pass button. It's the same issue as explained here: https://skypicker.slack.com/archives/C9K87QN6Q/p1531326915000311

**Comment by kantord** [comment]
> The FAQs section displays all the structures (pre-booking, after-booking, after-trip...) in this case.

Please note that Baggage is in "pre-booking" and "Documents and planning" (related to after booking) is in "after-booking". If we respect booking state when clicking Baggage/Boarding passes buttons, then simply no FAQs would be shown in this situation. So we either have to show all of the FAQs regardless of booking state (which would render this issue invalid) or we would have to re-define how the Baggage/Boarding passes buttons should work. For example we could just hide the buttons in certain booking states. cc @MRTNKCR @mjancik
