### ISSUE TITLE
add "manage" to urlProcessing

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#531]
our regex works for `kiwi.com/en/account/bookings/7442420` but not for `kiwi.com/en/manage/7442420` so when help is opened from MMB we aren't loading the correct booking

**Comment by MRTNKCR** [comment]
No internal testing for this issue? 🤔 I would pay an extra attention here since it can cause o lot of trouble compared to e.g. layout issues on tablet...

**Comment by jalbertsr** [comment]
This can't be tested in the standalone app, only when it is integrated on kiwi frontend.

I'm talking about this: 

`/account/bookings/XXXXX` work
![screenshot](https://i.gyazo.com/bb700c538e2d2049dfbf10289c8ae6db.png)

`/manage/XXXXX` dosent work
![screenshot](https://i.gyazo.com/238076865be89b786fbf16c8c5bb08d5.png)

I did unit test so it should be ok, but we'll test it again when opening MR in kiwi frontend

**Comment by MRTNKCR** [comment]
@jalbertsr Ok, thanks for the explanation, let's just make sure the QA in Brno knows about it and pays attention. Thank you!
