### ISSUE TITLE
Buses and trains should also be expandable 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#537]
![screenshot](https://i.gyazo.com/4d24f88a75a4094695d416a9991de553.png)

pls close the [gitlab issue #5023](https://gitlab.skypicker.com/frontend/frontend/issues/5023) when fixed

**Comment by vborszeki** [comment]
Where should the **Trains and Buses Info** link point to? @MRTNKCR @mjancik

**Comment by jalbertsr** [comment]
to the trains and buses article on smartfaq, for example https://www.kiwi.com/en/search/berlin-germany/dusseldorf-germany/2018-07-18_2018-08-18/no-return?help=%2Ffaq%2FRkFRQ2F0ZWdvcnk6OTA%3D%2Farticle%2FRkFRQXJ0aWNsZToxMjc%3D&transport=bus%2Ctrain

**Comment by MagdalenaAlmanova** [comment]
It is perfect :) Is it alright when in this case I couldn't touch on trip Bratislava to Santorini? 
![screen shot 2018-07-23 at 22 00 30](https://user-images.githubusercontent.com/37298895/43100374-73c25176-8ec5-11e8-9cb8-f5dd136415aa.png)
Thanks  @jalbertsr

**Comment by jalbertsr** [comment]
It always worked like this(that you need to click first to "show more trips") another thing would be if we want to change that behaviour. I'll ask about it.
