### ISSUE TITLE
Boarding pass button doesn't work after typing into search field

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#538]
pls see: https://monosnap.com/file/i9ffL2CSsD469hBuez7M921hLeNkMZ
close [gitlab issue #5028](https://gitlab.skypicker.com/frontend/frontend/issues/5028) when fixed

**Comment by MagdalenaAlmanova** [comment]
It works in Opera, Chrome, and Firefox but not in Safari 11.1.1.. :( There is missing one part of Smart FAQ. 
![screen shot 2018-07-12 at 21 19 31](https://user-images.githubusercontent.com/37298895/42654583-64901080-8619-11e8-9313-a6930c7ade31.png)

@jalbertsr

**Comment by jalbertsr** [comment]
Very strange, but probably also related to issue: #502, retest after closing #502.

**Comment by MagdalenaAlmanova** [comment]
👍
