### ISSUE TITLE
Search restricted to proper FAQ structure

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#540]
As a user, I should be only provided with categories/articles from the proper FAQs structure(pre-booking, after booking, emergency etc) while using the search feature.

**Comment by jalbertsr** [comment]
whats the difference between this issue and https://github.com/kiwicom/smart-faq/issues/459 ?

**Comment by MRTNKCR** [comment]
Shit, looks like a duplicity 🤦‍♂️ Sorry guys, I will archive this one.

**Comment by MRTNKCR** [comment]
And "shit" once again, it was moved to QA now. Is there any way to remove it completely, before i cause more damage?

**Comment by jalbertsr** [comment]
removed :)
