### ISSUE TITLE
FAQs are not loading the correct faqs categories for the booking status

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#544]
Repro steps:

- user uses iPhone or other mobile device to access SmartFAQ
- user logs into SmartFAQ

Expected
- list of FAQs is updated according to booking status

Actual
- list of FAQs is not updated until the booking info is clicked & expanded

Pls add cypress tests for this or adjust the existing one.

**Comment by jaroslav-kubicek** [comment]
can you elaborate more pls? reproduction steps?

**Comment by jalbertsr** [comment]
Since we have to load the booking before the faqs to know the status, first easy solution that comes to my mind is extending the booking tab by default, so the booking will be loaded first, the second solution is loading the booking without having it rendered?

**Comment by jaroslav-kubicek** [comment]
stealing from @kantord   🤜
