### ISSUE TITLE
Do not show section category in breadcrumbs

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#552]
Repro steps
- User logs in
- User clicks on Boarding passes button

Actual
- "After booking" is shown in breadcrumbs

Expected
- Do not show the section category in breadcrumbs

![screen shot 2018-07-17 at 17 55 14](https://user-images.githubusercontent.com/2174629/42829915-a379908a-89ea-11e8-8bff-71fd482ead06.png)

Solving this related issue will help: https://github.com/kiwicom/graphql/issues/276

**Comment by MagdalenaAlmanova** [comment]
💯
