### ISSUE TITLE
Add possibility to show emergency warnings

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#557]
<img width="427" alt="screen shot 2018-07-19 at 12 29 58" src="https://user-images.githubusercontent.com/2174629/42937506-7c1bc4b6-8b4f-11e8-8387-4b86d42339f9.png">

Acceptance criteria
- Emergency warning will be special article in knowledgebase api
- if the article is present, it means there is some emergency to be displayed to customer
- if the article is not present, it means there is no warning to be displayed

Note GraphQL will need to be updated too.

Zeplin: https://zpl.io/V1qE7ZJ

**Comment by MagdalenaAlmanova** [comment]
The symbol of the exclamation mark should be higher, I think. Where is a title of emergency warning? 
![screen shot 2018-08-14 at 21 22 10](https://user-images.githubusercontent.com/37298895/44113578-d8215be0-a008-11e8-965c-6d4142e9b9ab.png)
If it is acceptable, please move it into right column :) Thank you :) 👍

**Comment by jalbertsr** [comment]
since we use exponea instead of knowladgebase API, we don't have data for a specific location or a title, should we use a generic title? or is ok for now? @mjancik

**Comment by mjancik** [comment]
Well, I just found out, that we are going to use exponea instead of knowledgebase. Which basically makes it just a banner you can't open into an article. That also means we need to visually adjust it, because now it looks the same as an article and suggests that it can be clicked on and opened.

**Comment by mjancik** [comment]
If it is just an alert it should use alert message component from orbit.
