### ISSUE TITLE
Search in header

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#558]
According to our data, most of our users start by clicking on categories and do not search. However, they do search when clicking through categories was not successful for them.

To help them with this use case we will make search smaller and put it into the header (so there is a bigger focus on tiles in the left panel) and make it available also when they are in an article. 

At the same time, we will get rid of the help centre link.

Zeplin (it is in the screen with emergencies): https://zpl.io/V1qE7ZJ

**Comment by MagdalenaAlmanova** [comment]
👍
