### ISSUE TITLE
Clicking trans and buses link

### ISSUE THREAD

**Issue by mjancik** [kiwicom/smart-faq#568]
Weird behavior when clicking the link on the search page.

Repro steps:
- User clicks on a link to open a specific article about trains
- User clicks on "< Search" in header

Expected
- Root list of FAQ categories is shown

Actual
- the blank page is shown

Video: https://monosnap.com/file/E14GM0ZDlv6f4nOeMUEzWfQcS7ThKX

**Comment by jaroslav-kubicek** [comment]
is it still valid after yesterday release? works for me now @mjancik

**Comment by mjancik** [comment]
Yes, still getting this bug

**Comment by jaroslav-kubicek** [comment]
Ahh, I understand now 😅   it's after clicking on "< Search"
