### ISSUE TITLE
Boarding passes button broke after clicking on "Home"

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#574]
Repro steps
- User clicks on "Boarding passes"
- Boarding passes info is shown
- User clicks on "Home" in breadcrumbs, button is unselected although boarding passes info is still displayed

Expected
- clicking on "Boarding passes" button should hide the info about boarding passes

Actual
- nothing happens

See video below:

![boarding_passes](https://user-images.githubusercontent.com/2174629/43229658-dbbbcffe-9065-11e8-8730-b753443e8757.gif)

**Comment by MagdalenaAlmanova** [comment]
🥇 💯
