### ISSUE TITLE
Race condition with doubled login buttons

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#585]
For non-standard weird resolution, there might be two login buttons.

<img width="429" alt="screen shot 2018-07-27 at 20 21 19" src="https://user-images.githubusercontent.com/2174629/43340129-a2f9ce10-91db-11e8-8c44-b857dea3fbb8.png">

**Comment by MagdalenaAlmanova** [comment]
:) good job
