### ISSUE TITLE
Check email page in mobile landscape is showing just 1/3 full page

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#589]
Check your email inbox in landscape mode is showing just 1/3 full page, It is impossible to scroll...

![screenshot](https://user-images.githubusercontent.com/37298895/43344293-6f5866c6-91e9-11e8-9186-cab422712a3a.JPG)

**Comment by MagdalenaAlmanova** [comment]
It is ok when there is missing the picture? Because in portrait mode is present and there no. I didn't find design in zeplin for this case :/ 

 
![image](https://user-images.githubusercontent.com/37298895/43417603-b6e315fa-943b-11e8-9822-4e7684502998.png)

**Comment by vborszeki** [comment]
@MagdalenaAlmanova yes, I have omitted the image for usability reasons, as on other landscape screens, in order to avoid scrolling to the main content/message.
