### ISSUE TITLE
Refactor search field

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#614]
Refactor search field for desktop to be in header:

<img width="714" alt="screen shot 2018-08-03 at 10 30 10" src="https://user-images.githubusercontent.com/2174629/43633035-4938aeb4-9708-11e8-9929-98e5f5e74fa2.png">

Zeplin: https://zpl.io/V1qE7ZJ

**Comment by jalbertsr** [comment]
duplicated issue https://github.com/kiwicom/smart-faq/issues/558
