### ISSUE TITLE
List of FAQ doesn't reflect the booking status on mobile

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#631]
When accessing MMB with simple token on mobile device, e.g. `/en/content/manage/7388934/29b3de42-aa94-4b4d-8d28-d7d38b063332`, fetched list of FAQs is wrong.

Pls add cypress test as well.

**Comment by jalbertsr** [comment]
this is not only happening with simple token, this happens even if you're fully logged in, you only see the correct faqs once the booking is loaded, in mobile the booking is loaded after the user clicks in the booking tab -> related issue https://github.com/kiwicom/smart-faq/issues/544

**Comment by jaroslav-kubicek** [comment]
ha, thanks for explaining

**Comment by jaroslav-kubicek** [comment]
closing in favor of #544
