### ISSUE TITLE
It's not possible to go back from 'Select another booking page'

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#634]
See https://skypicker.slack.com/files/U9M0UMDA4/FC5BSSN1K/screenrecording_08-08-2018_21-46-24.mp4

See https://github.com/kiwicom/smart-faq/issues/416#issuecomment-411534986

**Comment by jaroslav-kubicek** [comment]
The link is not working, could you provide a description of reproduction steps, please? Thank you.

**Comment by kantord** [comment]
![ezgif com-resize](https://user-images.githubusercontent.com/3704904/43948168-5e802a7c-9c8a-11e8-895f-cf5b0cbb05a8.gif)

Here's Magda's video (from the link) as gif

**Comment by kantord** [comment]
Reproduction steps:
- Open SmartFAQ on mobile
- Open booking tab
- Tap 'select another booking'
- Try to scroll down to select a booking that is close to the bottom of the list

Note: will only work with a test account that has enough bookings, because the scroll issue only comes after about 500px of scrolling.

**Comment by kantord** [comment]
Here's the video too https://gfycat.com/gifs/detail/sentimentalhealthykingfisher

**Comment by MagdalenaAlmanova** [comment]
Thank you :) It is perfect :)
