### ISSUE TITLE
Glitch when typing into search and scrolling down

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#635]
See https://github.com/kiwicom/smart-faq/issues/416#issuecomment-411534986

![43861641-c1541bec-9b57-11e8-9a3d-7734cd7a9690](https://user-images.githubusercontent.com/3704904/43887868-4e88239c-9bc0-11e8-989a-81cc5dc6d522.jpg)

**Comment by kantord** [comment]
![2018-08-13-105106_887x1138_scrot](https://user-images.githubusercontent.com/3704904/44022139-0e7110a0-9ee7-11e8-945c-894c2e5b8ac9.png)

cant' reproduce. Probably fixed as collateral by some other pull request. Tried on my iPhone as well, but unfortunately the 5S' screen is too small to trigger the same layout anyway. @jalbertsr can you reproduce on your phone? I believe you have the same resolution.

**Comment by MagdalenaAlmanova** [comment]
👍
