### ISSUE TITLE
When I go to "select another trip" I cannot scroll down. 

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#636]
See https://github.com/kiwicom/smart-faq/issues/416#issuecomment-411534986

See https://skypicker.slack.com/archives/DBL479ENT/p1533759162000383

**Comment by MagdalenaAlmanova** [comment]
perfect :)) 👍

**Comment by jaroslav-kubicek** [comment]
I just tested it too and this is really huge improvement for UX 💯
