### ISSUE TITLE
Unwanted whitespace appearing when selecting a booking on mobile

### ISSUE THREAD

**Issue by vborszeki** [kiwicom/smart-faq#653]
When tapping on "Select another booking" on mobile and then selecting a booking, an unwanted whitespace appears above the FAQ articles while the header itself is not displayed.

See the video below:

![select_booking](https://user-images.githubusercontent.com/18072606/44085734-ac3fc80c-9fba-11e8-9835-232edf0c810e.gif)

**Comment by MagdalenaAlmanova** [comment]
Hmm.. On my iPhone, it is still here.

**Comment by vborszeki** [comment]
solved in #673
