### ISSUE TITLE
Update Orbit components to 0.7.0

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#659]
FYI: please note this requires update of orbit components also on frontend when integrating these changes

**Comment by vborszeki** [comment]
@MagdalenaAlmanova in this issue our UI elements were updated to use a newer version of our component library, there is no new functionality, so what is testable here, is that the UI is not broken.

**Comment by MagdalenaAlmanova** [comment]
It is alright when I am on the article and I want to search for some information but I couldn't? I pressed enter but nothing displayed. 
![screen shot 2018-08-21 at 22 09 37](https://user-images.githubusercontent.com/37298895/44426434-ed4d3800-a58e-11e8-9e78-41bc0b87ff52.png)

Thanks @vborszeki

**Comment by MagdalenaAlmanova** [comment]
My mentioned bug is still present. Please, If it is ok, move it to "done" column. Thanks
