### ISSUE TITLE
Fix failing GraphQL queries

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#661]
As @mrtnzlml says:

> There are thousands of your queries failed and it’s happening for a long time already [..]. For example `NearestBookingQuery` failed 1594x in last 24 hours.

**Comment by jaroslav-kubicek** [comment]
The problem was that `NearestBookingQuery` was sent before url with specific bookingId was processed

**Comment by mrtnzlml** [comment]
Hi, what is the progress here?

**Comment by mrtnzlml** [comment]
When is this fix going to be released? We still have _"1293 operations failed while executing path `nearestBooking`"_ in last 24 hours.

**Comment by jalbertsr** [comment]
Next week for sure, hopefully on Monday.
