### ISSUE TITLE
Improve feedback form

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#668]
The current implementation of the feedback form within the articles is not good, the pax try to contact the CS via this form. Therefore, we will change it: https://marvelapp.com/342f42a/screen/46847823

The pap can select 👍 or 👎 on the article. If he cliks 👍 , he goes direcly to the "Thank you" message. If he clicks 👎 , we ask him why the article wasn't helpful and the we allow him to share another feedback via the form. At the end, he sees the "Thank you" message.

Knowledgebase endpoints are ready.

**Comment by MagdalenaAlmanova** [comment]
Perfect :)
