### ISSUE TITLE
mobile responsive design screens

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#67]
Acceptance criteria:
Pages according to designs: 
 - [x] [Intro page](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ab3c41214a225f59eaf9761)
- [x] [Login](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ab3c412838d05a454d613b7)
- [x] [Check email](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ab3c412e86a6ceb9ed66773)
- [x] [New password](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ace03b684aaee9f55dfbe8a)
- [x] [Kiwi login](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ace03b684aaee9f55dfbe8a)

**Comment by MagdalenaAlmanova** [comment]
I am not sure whether I understood this issue right. When I opened the link **https://introduce-smart-faq.fe.staging.kiwi.com/en/** on my iPhone and tapped on the button Help, it showed me "**old Help**". 

When I tested this on iPad Pro, there was already identified bugs plus **one new**. When I rotated tablet into widescreen position, the login page was not shown as a whole. I could not scroll down and tap on Kiwi login, only the main screen on the left was scrolled down. 
This bug occurred in **Chrome version 65.0** and also sometimes in **Safari**. Look at the screenshot.

![fullsizerender](https://user-images.githubusercontent.com/37298895/38892593-f7c93654-4287-11e8-9ca0-3f181c91110e.jpg)

_Note: In every browser on the iPad, I had a problem with typing into the right textbox._ 

**If I had to do something else, please let me know.** @jalbertsr 

Thank you,
Meggy

**Comment by jalbertsr** [comment]
@MagdalenaAlmanova  this issue should be tested in https://kiwicom.github.io/smart-faq/, sorry for the confusion, from now on I'll try to post where you have to test it. 

Nice you mention iPad, because is something we haven't talk about, do we plan to support iPad with special designs or should it look the same as desktop, but somehow adapted @MRTNKCR ?

**Comment by MagdalenaAlmanova** [comment]
It looks gorgeous. @jalbertsr 
Nevertheless, I have one question, maybe for the designer, sometimes  **Email** is used and other time **E-mail** over the textbox. E.g. **_M1-1-2 Help_**, **_Forgot pass 1_** (e-mail) and **_M1-2a-0 Help_** is email. I guess that should be unified, alright? Also, 

> e.g. your@email.com

or 

> your@email.com

 into textboxes. 

How can I get to the new password page? Because when I tapped my email into page "Forgot password", it sent me a link, and when I opened this link, it is on original Kiwi.com website.

Thank you for your answers.

**Comment by jalbertsr** [comment]
@mjancik about https://github.com/kiwicom/smart-faq/issues/67#issuecomment-382498468 should we unify this fields or are ok like this? 

@MagdalenaAlmanova about the new password page it isn't able yet because we have to talk with guys in Brno, to change some things.

**Comment by mjancik** [comment]
@jalbertsr Yes, it should be unified and say: **email** not e-mail. According to our copywriting rules.
