### ISSUE TITLE
Articles are not fetched for root categories

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#670]
Since there's only one category in this booking state, we're forcing the user to make a completely unnecessary click

![2018-08-17-153202_2746x1575_scrot](https://user-images.githubusercontent.com/3704904/44268748-be536100-a232-11e8-8f4d-04e9e90dcfb1.png)

UPDATE: There is a bug in our root category query - we are not fetching articles for root categories (and it's not even possible)

- [ ]  step I. create new FAQ query merging `allFAQCAtegories` and `FAQCategory` into one query
- [ ] step II. update SmartFAQ to use this query and display articles on the root level

**Comment by kantord** [comment]
@jaroslav-kubicek since your comment
> UPDATE: There is a bug in our root category query - we are not fetching articles for root categories (and it's not even possible)

Changes the meaning of the entire issue, I'm changing the title :-)

**Comment by kantord** [comment]
>we are not fetching articles for root categories (and it's not even possible)

Maybe I don't understand the problem correctly, because it seems perfectly possible to me:

![2018-08-29-160103_2691x1335_scrot](https://user-images.githubusercontent.com/3704904/44792679-c1d8d780-aba4-11e8-8eb2-971935243bc9.png)

I think this is the exact same root category.

**Comment by MagdalenaAlmanova** [comment]
Great :)
