### ISSUE TITLE
Fix minor scroll issues

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#673]
Issue originally from here: https://gitlab.skypicker.com/frontend/frontend/merge_requests/5677#note_728294

>   [ ] guys on mobile now when i select another booking, the header is missing until i scroll, and it is not consistent in a way that if i scroll a little bit downwards it appears then disappears again.
>
>  [ ] and when it disappears it leaves a very large blank space behind it, tbh I hope we can make the animation of the header disappearing more seamless here.

**Comment by MagdalenaAlmanova** [comment]
👍

**Comment by jalbertsr** [comment]
isn't this is issue the same as https://github.com/kiwicom/smart-faq/issues/653 ?

**Comment by vborszeki** [comment]
@jalbertsr yes, it is 🙂
