### ISSUE TITLE
Back button should not rely on history

### ISSUE THREAD

**Issue by kantord** [kiwicom/smart-faq#685]
@mrtnzlml pointed out issues with how our back button works:

-  if you end up on the login screen using a link, the back button doesn't do anything, so you cannot proceed without login
- If you open a category using a link, you cannot go back
- If you open an article using a link, you can only go back one level and you'll end up in a loop

The fundamental issue is that we don't have history when we open the page using a link, so no wonder it doesn't work.

We could re-construct history, however it'd probably make sense to not use it at all, as usually the order of navigation doesn't matter, people normally just want to go one level back

Based on the proposal of @jaroslav-kubicek, the back button should work the following way, even after page refresh:
- [x] when on Sign In page, it should go to the homepage
- [x] when on Login via Kiwi.com email & password page, it should go to Sign In page
- [x] when on Forgotten password, it should go to Login via Kiwi.com email & password page
- [x] when in the FAQ category, it should go one level up in categories
- [x] when in FAQ article, it should go to the category to which the article belongs
- [x] when in FAQ article displayed from search, it should return to search

**Comment by jaroslav-kubicek** [comment]
**Proposed solution how the back button should work:**

- When in the FAQ category, it should go one level up in categories
- When in FAQ article, it should go to the category to which the article belongs
- When in FAQ article displayed from search, it should return to search
- When on Sign In page, it should go to the homepage
- When on Login via Kiwi.com email & password page, it should go to Sign In page
- When on Forgotten password, it should go to Login via Kiwi.com email & password page

all points should work even after page refresh.

+ Add cypress tests verifying all these points

**Comment by kantord** [comment]
I agree with all the points.

> When in the FAQ category, it should go one level up in categories

This is already implemented, that's what's causing the loops (combined with history)
