### ISSUE TITLE
Further improvements in guarantee chat

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#725]
Following the first step done in #667, let's improve the chat

- [x] add analytics
- [x] reconnect after page reload
- [x] when clicking on "back" button while the chat is open, show confirm just like for closing
- [ ] show guarantee chat also 4 hours before the flight that precedes following flight covered by Kiwi.com guarantee

**Comment by MagdalenaAlmanova** [comment]
I think, that it is ok :)
