### ISSUE TITLE
Proper ordering of boarding passes by flights.

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#728]
As a user, I want to see a list of my boarding passes ranked according to departure date. Example:

Here is an itinerary Prague - Oslo, Oslo - New York, New York - Stockholm, Stockholm - Prague.

![snimek obrazovky 2018-09-13 v 10 16 01](https://user-images.githubusercontent.com/7661448/45476463-426c0c00-b73f-11e8-8d38-dd1fd260e67b.png)

This is what I currently see in Smart FAQ BP overview:

![snimek obrazovky 2018-09-13 v 10 15 35](https://user-images.githubusercontent.com/7661448/45476533-6c253300-b73f-11e8-98ca-3f89043d1818.png)

I want to see the BPs in the following order:

![snimek obrazovky 2018-09-13 v 10 16 26](https://user-images.githubusercontent.com/7661448/45476500-5adc2680-b73f-11e8-923a-5bb97640b4e0.png)

**Comment by MagdalenaAlmanova** [comment]
Good job :)
