### ISSUE TITLE
BP component hidden for accounts with no bookings

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#732]
As a user with no bookings, I don't want to see the empty Boarding pass component on top of the Documents and planning article.

![snimek obrazovky 2018-09-13 v 14 58 28](https://user-images.githubusercontent.com/7661448/45531982-718f8580-b7f2-11e8-9308-50f967b963c9.png)

**Comment by MagdalenaAlmanova** [comment]
Great
