### ISSUE TITLE
Add static login components into nitro

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#741]
Let's help to ship new login form faster by adding static HTML+CSS components into nitro.

Important DOCs to read before you start: https://gitlab.skypicker.com/frontend/nitro/tree/master/docs

Actions like submit and click handlers should be implemented just as dump callback props, e.g. `onAction={this.handleAction}`

Zeplin: https://zpl.io/aRYKOy0

**Comment by kantord** [comment]
Split up to smaller issues
