### ISSUE TITLE
Don't use translations in ErrorBoundary

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#782]
cc @jalbertsr 

<img width="503" alt="screenshot 2018-10-01 16 11 43" src="https://user-images.githubusercontent.com/2174629/46293772-bce8b880-c594-11e8-8921-2c9070d93b2c.png">

**Comment by jalbertsr** [comment]
aah, of course, ErrorBoundary is in the top of all contexts...

**Comment by jalbertsr** [comment]
closed here https://gitlab.skypicker.com/frontend/smart-faq/merge_requests/763

**Comment by MagdalenaAlmanova** [comment]
Is it ok? 
![screen shot 2018-10-03 at 20 48 24](https://user-images.githubusercontent.com/37298895/46432151-d123e580-c74d-11e8-9bfa-eeaf07573618.png)
