### ISSUE TITLE
Images not loading on the new stage

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#79]
Images, icons etc are not loading on the new stage (https://introduce-smart-faq.fe.staging.kiwi.com/)

(MacOS, Safari, Chrome)

![snimek obrazovky 2018-04-12 v 12 05 49](https://user-images.githubusercontent.com/7661448/38671321-5fea2b30-3e4b-11e8-8894-14ab765ce3be.png)

**Comment by jalbertsr** [comment]
Images should be uploaded to some CDN during NPM publish, probably images.kiwi.com CDN Amazon CloudFront.

**Comment by MagdalenaAlmanova** [comment]
I was testing again everything, i.e. : **"Need help"** page, **"Sing in"** page, **"Check your email inbox"** page, social logins buttons, **"Kiwi.com account"** page, and **"Help"** page. 

I found two mistakes. The first one is in the **"Sign in"** page, where the button is not in the right place on the page. See on the screenshot.

![screen shot 2018-04-15 at 18 24 33](https://user-images.githubusercontent.com/37298895/38780868-506c7912-40dd-11e8-97b4-6faa4df6c0ab.png)
 
The second one is in Firefox, where I cannot write into every box. When I scroll over the box and start typing, it to redirects me to another box. Look at the screenshot.

![screen shot 2018-04-15 at 18 35 11](https://user-images.githubusercontent.com/37298895/38780929-f84655fe-40dd-11e8-8c60-53e1c6a75aaf.png)

It was tested on macOS High Sierra 10.13.4 in Safari v. 11.1, Mozilla Firefox v. 59.0.2, Chrome 65.0 and Opera 52.0.

Thank you,
Meggy

**Comment by MRTNKCR** [comment]
@MagdalenaAlmanova I reported both these bugs last week, but added them as separate issues - here they are: 

https://github.com/kiwicom/smart-faq/issues/82
https://github.com/kiwicom/smart-faq/issues/80

I'm moving this card to Done.

FYI @jalbertsr

**Comment by MagdalenaAlmanova** [comment]
I apologize, my mistake. But the second error I saw was in Firefox and not in Chrome.

@MRTNKCR
