### ISSUE TITLE
Smart FAQ login: wrong layout

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/smart-faq#80]
Login button is not aligned correctly on the new stage (https://introduce-smart-faq.fe.staging.kiwi.com/cz/):

![snimek obrazovky 2018-04-12 v 12 12 46](https://user-images.githubusercontent.com/7661448/38671250-3457a56a-3e4b-11e8-829b-0a7c201b36c3.png)

(MacOS, Safari, Chrome)

**Comment by jalbertsr** [comment]
test it here: https://introduce-smart-faq.fe.staging.kiwi.com/en/

**Comment by MagdalenaAlmanova** [comment]
It is perfect 💯
