### ISSUE TITLE
Broken images in <img> elements without sizes makes content jump. 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#85]
Broken images in `img` elements without sizes makes content jump. 

See [Zepplin](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/dashboard) designs to look for the appropriate sizes.

**Comment by jalbertsr** [comment]
This happened when we had broken/not loaded images in https://introduce-smart-faq.fe.staging.kiwi.com/ , if you don't find content jumping or wrong placed feel free to close the issue.

**Comment by kantord** [comment]
Feel free to reopen the issue if you can reproduce
