### ISSUE TITLE
faq articles in search have too large headings. 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#87]
Text is out of the box for FAQ articles in search.
Please see discussion on #29 for more details.

Match design: [Zeplin](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aa98f807e4ac0f30f266e1c)

**Comment by jaroslav-kubicek** [comment]
https://user-images.githubusercontent.com/37298895/39327529-92d8947a-4998-11e8-9998-b80274cc9fc8.png
