### ISSUE TITLE
Add breadcrumb navigation on FAQ article detail page

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#90]
*Acceptance criteria*
- when a user is on FAQ article detail screen, he can click on any breadcrumb displayed above article title to navigate back to that specific category

Zeplin: https://zpl.io/aM48YJr or in app zpl://screen?sid=5aa98f7f3820cb498e96a09a&pid=5a8e8992554d385c76ad5aeb

**Comment by MagdalenaAlmanova** [comment]
👍
