### ISSUE TITLE
Show proper error when requests to static FAQs fails

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#96]
**Acceptance criteria**
- instead of a bare text message, proper error according to design is displayed, when something goes wrong

Update: [Zeplin design](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5af550143745ab9c208a1ffb)

**Comment by MagdalenaAlmanova** [comment]
I tried the error page and there were two sentences missing:"Sign out. Then sign in again." 

Demo v.
![screen shot 2018-05-15 at 21 59 16](https://user-images.githubusercontent.com/37298895/40080525-8707f06c-588b-11e8-8761-aac9d4961361.png)

Prototype v.
![screen shot 2018-05-15 at 21 58 18](https://user-images.githubusercontent.com/37298895/40080542-916d0182-588b-11e8-94f3-89183a30bff8.png)

Thanks. :)

**Comment by MagdalenaAlmanova** [comment]
All right, I am sorry. I didn't know about it. Could you please write the comment when making a similar decision next time? It really helps me and you.
