### ISSUE TITLE
Add Flight info dropdown/accordion

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#99]
The Upcoming booking page is ready and already has an (incomplete) Accordion component. So we can add the flight info once the design is added to Zeplin. @MRTNKCR @mjancik

Marvel link: https://marvelapp.com/7iihb90/screen/39641486

**Update:** zeplin link: https://zpl.io/adMXoOp

**Comment by MagdalenaAlmanova** [comment]
I think this does not work. When I clicked on the down arrow, they changed on the up arrow but nothing was showed down. See on the screenshot. 

![screen shot 2018-05-15 at 21 46 19](https://user-images.githubusercontent.com/37298895/40079985-ed2f9036-5889-11e8-9374-64e0907c8790.png)

Thanks

**Comment by MagdalenaAlmanova** [comment]
I found some minor mistakes:
1) `The arrow` between two destinations should have a different color and abbreviations of destinations are not in parenthesis (PRG). 
Demo v. 
![screen shot 2018-05-28 at 21 45 14](https://user-images.githubusercontent.com/37298895/40627654-79bcc57e-62c0-11e8-95c2-d4c5fc523020.png)
Prototype v. 
![screen shot 2018-05-28 at 21 45 24](https://user-images.githubusercontent.com/37298895/40627663-82c603f6-62c0-11e8-8e90-7d399cfe0761.png)
2) `The date format` is not according to design and the date next to the calendar should be **bold**.
Demo v.
![screen shot 2018-05-28 at 21 53 17](https://user-images.githubusercontent.com/37298895/40627836-90442994-62c1-11e8-9777-57264b659f79.png)
Prototype v.
![screen shot 2018-05-28 at 21 53 04](https://user-images.githubusercontent.com/37298895/40627841-98e3d630-62c1-11e8-929d-8e10acff5c18.png)
3) `The flight duration` text should end at the end of airline icon and should be without _"min"_.
Demo v.
![screen shot 2018-05-28 at 21 58 28](https://user-images.githubusercontent.com/37298895/40628055-fcca3760-62c2-11e8-87fd-7d789753edc0.png)
Prototype v.
![screen shot 2018-05-28 at 21 58 39](https://user-images.githubusercontent.com/37298895/40628060-04060022-62c3-11e8-9b0a-92dc340a2156.png)

Thanks

**Comment by jalbertsr** [comment]
I see almost every design in zeplin have parenthesis  `()` except for two that doesn't have it. what is correct @mjancik ?

**Comment by git-toni** [comment]
Thanks for the feedback Maggy.

1. Should be fixed.
2. Date format depends on country selected, if you choose US you'll see the comma as in the prototype. Date is not specified as bold in the designs, but I agree it really looks like it is, so I made it bold.
3. Should be fixed.

**Comment by jaroslav-kubicek** [comment]
> Date is not specified as bold in the designs, but I agree it really looks like it is, so I made it bold.

please don't do such assumptions, it's neither bold nor normal, but " medium" - `font-weight: 500`. Looks like something between small `Heading` and `Text` component in orbit, please consult with @mjancik

**Comment by mjancik** [comment]
Abbreviations should not be in parenthesis. It has been a decision made by designers here in our team, mainly to make it look less technical.

Date formatting should behave as you already mentioned above by @jalbertsr 

The weight of the font has been medium, since the design of this entire component is identical with the component on frontend and it has been made before Orbit was introduced. However, I switched it in the prototype to bold to make it Orbit compliant for the future.
